@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}
class Organization{
    name
    address
}

class VFM {

}


class GreenSpace {
    name
    address
    dimension
}

class Garden {

}

class MediumSizedPark {

}

class LargeSizedPark {

}
class Vehicle{
    plate id
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}

class VehiclesCheckUp {
    plate id
}

class Brand{
name
}

class Model{
name
}

Collaborator <|- VFM
VFM "1" -- "1..*" VehiclesCheckUp: lists >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
GreenSpace "1" - "1..*" Collaborator: contains >
VehiclesCheckUp "1" -- "1..*" Vehicle: contains >
GreenSpace "1" - "1..*" Vehicle: has >
Organization "1" - "1..*" GreenSpace: owns >
Organization "1" -- "1..*" Collaborator: works for <
GreenSpace "1" - "1" VehiclesCheckUp: has >
Vehicle "1" - "1" Brand: has >
Brand "1" - "1..*" Model: has >
Organization "1" - "1..*" Vehicle: owns >
@enduml