@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class VFM {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class VehiclesCheckUp {
    plate id
}
class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}
class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}



Collaborator <|-- VFM
VFM "1" -- "1..*" VehiclesCheckUp: lists >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
GreenSpace "1" -- "1..*" Collaborator: contains >
VehiclesCheckUp "1..*" -- "1  " GreenSpace: has <
Vehicle "1..*" -- "1" VehiclesCheckUp: has <
GreenSpace "1" -- "1..*" Vehicle: has >

@enduml