@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Job {
    - name: String
}

class HRM {
}

class Organization {
    - name: String
    - address: String
}

HRM "1" --> "*" Job
Organization "1" -- "*" Job

@enduml