@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources\n Manager" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant "organization\n:Organization" as ORG
participant "job\n:Job" as Job

activate HRM

    HRM -> UI : asks to create a new job

    activate UI

        UI --> HRM : requests the name
    deactivate UI

    HRM -> UI : types requested the name
    activate UI

        UI --> HRM : requests confirmation
    deactivate UI

    HRM -> UI : confirms
    activate UI

        UI -> CTRL : registerJob(name)
        activate CTRL

            CTRL -> ORG : registerJob(name)
            activate ORG

            ORG -> Job**: register(name)
                ORG -> ORG: addJob(job)
                activate ORG

                ORG -> ORG: validateJob(job)
                activate ORG

            ORG --> CTRL : job
            deactivate ORG

            CTRL --> UI : job
        deactivate CTRL

        UI --> HRM: displays operation success
    deactivate UI

deactivate HRM

@enduml