@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Job {
    - name: String

    + Job(name)
}

class HRM {
}

class Organization {
    - name: String
    - address: String

    + register(name)
    + addJob(job)
    + validateJob(job)
}

class RegisterJobUI {

}

class RegisterJobController {
    + registerJob(name)
}

HRM "1" --> "*" Job
Organization "1" --> "*" Job
RegisterJobUI .> RegisterJobController
RegisterJobController .> Organization

@enduml