@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Job {
    - name: String

    + Job(name)
}

class HRM {
}

class RegisterJobUI {

}

class RegisterJobController {
    + CreateJobController(jobRepository)
    + registerJob(name)
}

class Repositories {
    - Repositories : Repositories
    + getInstance() : Repositories
    + getJobRepository() : Repositories
}

class JobRepository {
    + register()
}


HRM "1" --> "*" Job
Repositories "1" --> "*" Job
RegisterJobUI .> RegisterJobController
RegisterJobController .> Repositories : repositories
Repositories --> Repositories : instance
Repositories --> "1" JobRepository
JobRepository --> "1" Job
RegisterJobController .> JobRepository : jobRepository
RegisterJobController .> Job : job

@enduml