@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class HRM {
    + HRM()
    + generateTeamProposal(minimumSize, maximumSize, skills, collaborators)
}

class GenerateTeamProposalController {
    + GenerateTeamProposalController(skillRepository, collaboratorRepository, teamRepository)
    + listSkills()
    + getCollaborators()
    + generateTeamProposal(minimumSize, maximumSize, skills, collaborators)
    + createTeam(members)
}


class GenerateTeamProposalUI {
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillRepository()
    + getCollaboratorRepository()
    + getTeamRepository()

}

class SkillRepository {

}

class CollaboratorRepository {

}

class TeamRepository {
    + generateTeamProposal(minimumSize, maximumSize, collaborators, skills)
    + createTeam(members)
    + validateTeam(team)
    + addTeam(team)
}

class Team {
    - members : ArrayList<Collaborator>
    + Team(members)
}

class Collaborator {
    - name : String
    - birthdate : String
    - admissionData : String
    - address : String
    - mobileNumber : int
    - email : String
    - idDocumentType : String
    - idDocumentNumber : int
    + Collaborator(name, birthdate, admissionData, address, \nmobileNumber, email, idDocumentType, idDocumentNumber)
    + chooseMembers(minimumSize, maximumSize, collaborators, skills)
    + analyseCollaborator(skills)
}

class Skill {
    - name : String
    + Skill(name)
}

GenerateTeamProposalUI .> GenerateTeamProposalController
GenerateTeamProposalController .> Repositories : repositories
Repositories --> Repositories : instance

Repositories ---> "1" SkillRepository
Repositories ---> "1" CollaboratorRepository
Repositories ---> "1" TeamRepository

GenerateTeamProposalController .> SkillRepository : skillRepository
GenerateTeamProposalController .> CollaboratorRepository : collaboratorRepository
GenerateTeamProposalController .> TeamRepository : teamRepository

HRM "1" --> "*" Team : creates
Team  o-- "*" Collaborator : has
Collaborator  o-- "*" Skill : has

GenerateTeamProposalController .> Team : team
GenerateTeamProposalController .> SkillRepository : skills
GenerateTeamProposalController .> CollaboratorRepository: collaborators
SkillRepository --> Skill : has
CollaboratorRepository --> Collaborator : has
TeamRepository --> Team : has


@enduml