@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":GenerateTeamProposalController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "teamRepository\n:TeamRepository" as TEAMREP
participant "team\n:Team" as team

autonumber 17
-> CTRL : createTeam(teamProposal)

autonumber 17.1

activate CTRL
    group Create Team

        CTRL -> Repositories: getInstance()
        activate Repositories

            Repositories --> CTRL: repositories
        deactivate Repositories

        CTRL -> REP: getTeamRepository()
        activate REP

            REP --> CTRL: teamRepository
        deactivate REP

        CTRL -> TEAMREP: createTeam(teamProposal)
        activate TEAMREP

            TEAMREP -> team**: create(teamProposal)

                TEAMREP -> TEAMREP : addTeam(team)
                activate TEAMREP

                TEAMREP -> TEAMREP : validateTeam(team)
                activate TEAMREP

            TEAMREP --> CTRL: team

            deactivate TEAMREP

            deactivate TEAMREP

        deactivate TEAMREP

    end group

    autonumber 18
    <-- CTRL : team

@enduml