@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class HRM {
    + HRM()
    + generateTeamProposal(size, members)
}

class GenerateTeamProposalController {
    + GenerateTeamProposalController(skillRepository, collaboratorRepository, teamRepository)
    + listSkills()
    + chooseMembers(skills)
    + generateTeamProposal(size, members)
    + createTeam(teamProposal)
}


class GenerateTeamProposalUI {
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillRepository()
    + getCollaboratorRepository()
    + getTeamRepository()

}

class SkillRepository {

}

class CollaboratorRepository {

}

class TeamProposalRepository {
    - generateTeamProposal(size, members)
    - validateTeamProposal(teamProposal)
    - addTeamProposal(teamProposal)
}

class TeamRepository {
    - addTeam(team)
    - validateTeam(team)
    - create(teamProposal)
}

class TeamProposal {
    - size : int
    - members : ArrayList<Collaborator>
    + TeamProposal(size, members)
}

class Team {
    - teamProposal : teamProposal
    + Team(teamProposal)
}

class Collaborator {
    - name : String
    - birthdate : String
    - admissionData : String
    - address : String
    - contactInfo : int
    - idDocumentType : String
    - idDocumentNumber : int
    + Collaborator(name, birthdate, admissionData, address, \ncontactInfo, idDocumentType, idDocumentNumber)
}

class Skill {
    - name : String
    + Skill(name)
}

GenerateTeamProposalUI .> GenerateTeamProposalController
GenerateTeamProposalController .> Repositories : repositories
Repositories --> Repositories : instance

Repositories ---> "1" SkillRepository
Repositories ---> "1" CollaboratorRepository
Repositories ---> "1" TeamProposalRepository
Repositories ---> "1" TeamRepository

GenerateTeamProposalController .> SkillRepository : skillRepository
GenerateTeamProposalController .> CollaboratorRepository : collaboratorRepository
GenerateTeamProposalController .> TeamRepository : teamRepository
GenerateTeamProposalController .> TeamProposalRepository : teamProposalRepository

HRM "1" --> "*" Team : creates
Team  o-- "*" Collaborator : has
Collaborator  o-- "*" Skill : has

GenerateTeamProposalController .> TeamProposal : teamProposal
GenerateTeamProposalController .> Team : team
SkillRepository --> Skill : has
CollaboratorRepository --> Collaborator : has
TeamRepository --> Team : has
TeamProposalRepository --> TeamProposal : has


@enduml