@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":GenerateTeamProposalController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "teamProposalRepository\n:TeamProposalRepository" as TEAMPROREP
participant "teamProposal\n:TeamProposal" as teamProposal

autonumber 13
-> CTRL : generateTeamProposal(size, members)

autonumber 13.1

activate CTRL
    group Generate Team Proposal

        CTRL -> Repositories: getInstance()
        activate Repositories

            Repositories --> CTRL: repositories
        deactivate Repositories

        CTRL -> REP: getTeamProposalRepository()
        activate REP

            REP --> CTRL: teamProposalRepository
        deactivate REP

        CTRL -> TEAMPROREP: generateTeamProposal(size, members)
        activate TEAMPROREP

            TEAMPROREP -> teamProposal**: generateTeamProposal(size, members)

                TEAMPROREP -> TEAMPROREP : addTeamProposal(teamProposal)
                activate TEAMPROREP

                TEAMPROREP -> TEAMPROREP : validateTeamProposal(teamProposal)
                activate TEAMPROREP

            TEAMPROREP --> CTRL: teamProposal

            deactivate TEAMPROREP

            deactivate TEAMPROREP

        deactivate TEAMPROREP

    end group

    autonumber 14
    <-- CTRL : teamProposal

deactivate CTRL


@enduml