@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":GenerateTeamProposalController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "teamRepository\n:TeamRepository" as TEAMREP
participant "collaborator\n:Collaborator" as COLLAB
participant "team\n:Team" as team

autonumber 13
-> CTRL : generateTeamProposal(minimumSize, maximumSize, members)

autonumber 13.1

activate CTRL
    group Generate Team Proposal

        CTRL -> Repositories: getInstance()
        activate Repositories

            Repositories --> CTRL: repositories
        deactivate Repositories

        CTRL -> REP: getTeamProposalRepository()
        activate REP

            REP --> CTRL: teamProposalRepository
        deactivate REP

        CTRL -> TEAMREP: generateTeamProposal(minimumSize, maximumSize, skills, collaborators)
        activate TEAMREP

            TEAMREP -> COLLAB**: chooseMembers(collaborators, skills)
            activate COLLAB

            loop

                COLLAB -> COLLAB: analyseCollaborator(skills)
                activate COLLAB

            end
                COLLAB --> TEAMREP: members
                deactivate COLLAB

            deactivate COLLAB

            TEAMREP -> team**: generateTeamProposal(minimumSize, maximumSize, members)

                TEAMREP -> TEAMREP : addTeam(team)
                activate TEAMREP

                TEAMREP -> TEAMREP : validateTeam(team)
                activate TEAMREP

            TEAMREP --> CTRL: team

                deactivate TEAMREP

                deactivate TEAMREP
    end group

    autonumber 14
    <-- CTRL : team

deactivate CTRL


@enduml