@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

class Collaborator {
    name
}

class GreenSpace {
    name
    area
}

class ToDoListEntry {
    taskDescription
    urgency
    duration
}

class AgendaEntry {
    status
    completionDate
}

class Team {
    members
}

class ToDoList {
    toDoListEntries
}

class Agenda {
    agendaEntries
}

Collaborator "1" -- "0..*" ToDoListEntry : completes
GreenSpace "1" -- "0..*" ToDoListEntry : includes
ToDoListEntry "1" -- "1" Team : assignedTo
ToDoListEntry "1" -- "0..1" AgendaEntry : plannedIn
ToDoList "1" -- "0..*" ToDoListEntry : includes
Agenda "1" -- "0..*" AgendaEntry : includes
AgendaEntry "1" -- "1" ToDoListEntry : references
Team "1" -- "0..*" Collaborator : has

@enduml
