@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources\n Manager" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "jobRepository\n:JobRepository" as JOBREP
participant "job\n:Job" as Job

activate HRM

    HRM -> UI : asks to create a new job

    activate UI

        UI --> HRM : requests name
    deactivate UI

    HRM -> UI : types requested name
    activate UI

        UI --> HRM : requests confirmation
    deactivate UI

    HRM -> UI : confirms
    activate UI

        UI -> CTRL : registerJob(name)
        activate CTRL

            CTRL -> Repositories: getInstance()
            activate Repositories

            Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getJobRepository()
            activate REP

            REP --> CTRL: jobRepository
            deactivate REP

            CTRL -> JOBREP : registerJob(name)
            activate JOBREP

            JOBREP -> Job**: register(name)
                JOBREP -> JOBREP: addJob(job)
                activate JOBREP

                JOBREP -> JOBREP: validateJob(job)
                activate JOBREP

            JOBREP --> CTRL : job
                deactivate JOBREP

                deactivate JOBREP

            deactivate JOBREP

            CTRL --> UI : job
        deactivate CTRL

        UI --> HRM: displays operation success
    deactivate UI

deactivate HRM

@enduml