@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "jobRepository\n:JobRepository" as JOBREP
participant "job\n:Job" as Job

autonumber 11
-> JOBREP: registerJob(name)

autonumber 11.1
activate JOBREP
    group Register Job

        JOBREP -> Job**: register(name)
        JOBREP -> JOBREP: addJob(job)
        activate JOBREP

            JOBREP -> JOBREP: validateJob(job)
            activate JOBREP

    end

    autonumber 12
    <-- JOBREP : job
deactivate JOBREP


@enduml