@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : request to assign skills to a collaborator
    activate System

        System --> HRM : displays a list of available skills
    deactivate System

    HRM -> System : selects collaborator skills
    activate System

        System --> HRM : requests confirmation
    deactivate System

    HRM -> System : not confirm
    activate System

        System --> HRM : returns the list of skills (selected and not only) \n and asks for a review
    deactivate System

    HRM -> System : review and change (or not)
    activate System

        System --> HRM : requests confirmation
    deactivate System

    HRM -> System : confirms
    activate System

        System --> HRM : displays operation success
    deactivate System

@enduml