@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green\nSpaces\nManager\n(GSM)" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a topographic survey, of the pipelines between water points

    activate System

        System --> Employee : asks for confirmation
    deactivate System
    Employee -> System : Confirms that he wants to create the topographic survey
        activate System

            System --> Employee : shows a topographic survey, of the pipelines between water points
        deactivate System


@enduml