@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ListMaintenanceUI{

}
class ListMaintenanceController{
}
class MaintenanceRepository{
}
class VFM{
}
class Repositories{
}

ListMaintenanceUI .> ListMaintenanceController
ListMaintenanceController ..> Repositories : repositories
Repositories -> Repositories : instance
ListMaintenanceController .> MaintenanceRepository: maintenanceRepository
Repositories ---> MaintenanceRepository
ListMaintenanceUI ..> VFM : list
@enduml