@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as GRH
participant ":System" as System

activate GRH

    GRH -> System : asks to create a new profession
    activate System

        System --> GRH : requests data (i.e. designation, descriptions,\nmedium salary)
    deactivate System

    GRH -> System : types requested data
    activate System

        System --> GRH : shows a list of required education levels and\nasks to select one
    deactivate System

    GRH -> System : selects a required level of education
    activate System

        System --> GRH : shows a list of competences and asks you to\nselect all the ones you need
    deactivate System

    GRH -> System : selects all the necessary competences
    activate System

        System --> GRH : presents a list of sectors of activity and asks\nyou to select one
    deactivate System

    GRH -> System : selects a sector of activity
    activate System

        System --> GRH : shows all data and requests confirmation
    deactivate System

    GRH -> System : confirms data
    activate System

        System --> GRH : displays operation success
    deactivate System

@enduml