@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Human Resources\nManager" as GRH
participant ":System" as System

activate GRH

    GRH -> System : asks to create a new job
        activate System

            System --> GRH : requests the designation
        deactivate System

        GRH -> System : types requested the designation
        activate System

            System -> GRH : displays error message and requests\ndesignation correction
        deactivate System

        GRH -> System : checks and corrects the designation
        activate System

            System --> GRH : requests confirmation
        deactivate System

        GRH -> System : confirms data
        activate System

            System --> GRH : displays operation success
        deactivate System
@enduml