@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Three

autonumber

actor "Human Resources\nManager" as GRH
participant ":System" as System

activate GRH

    GRH -> System : asks to create a new job
        activate System

            System --> GRH : requests the designation
        deactivate System

        GRH -> System : types requested the designation
        activate System

            System --> GRH : requests confirmation
        deactivate System

        GRH -> System : not confirm
        activate System

            System --> GRH : returns the designation and asks for revision
        deactivate System

        GRH -> System : review and change (or not)
        activate System

            System --> GRH : requests confirmation
        deactivate System

        GRH -> System : confirms
        activate System

            System --> GRH : displays operation success
        deactivate System

@enduml