@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human\nResources\nManager\n(HRM)" as HRM
participant ":RegisterSkillsUI" as UI
participant ":RegisterSkillsController" as CTRL
participant Repositories
participant "repositories:Repositories" as REP
participant "skillsRepositories" as SREP
participant "skill:Skill" as SKILL

activate HRM


        HRM -> UI : asks to register some SKILL
        activate UI

                UI -> HRM : requests the skill name
        deactivate UI
        HRM -> UI: Types requested data
        activate UI

                UI -> HRM : Shows the SKILL and asks for confirmation
        deactivate UI
        HRM -> UI : Confirms SKILL.
        activate UI

                UI -> CTRL: registerSkills(name)

                activate CTRL

                        CTRL -> Repositories: getInstance()

                        activate Repositories

                                Repositories -> CTRL: repositories
                        deactivate Repositories

                        CTRL -> REP: getSkillsRepository()
                        activate REP

                                REP -> CTRL: skillsRepository
                        deactivate REP
                        CTRL -> SREP: registerSkills(name)
                        activate SREP

                                SREP -> SKILL**: register(name)
                                activate SREP

                                SREP -> SREP: addSkill(skill)
                                        activate SREP
                                        SREP -> SREP: validateSkill(skill)





                                SREP -> CTRL: skill
                                        deactivate SREP
                                deactivate SREP
                        deactivate SREP

                        CTRL -> UI: skill
                deactivate CTRL

                UI -> HRM: displays operation success
        deactivate UI
deactivate HRM

@enduml