@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet Manage" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle for check-up
    activate System
    loop

        System --> Employee : shows list of registered vehicles
    deactivate System

    Employee -> System : choses vehicle for check-up
    activate System
    end
        System --> Employee : requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml