@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "toDoList\n:toDoList" as toDoList
participant "entry\n:Entry" as entry
participant "statusList\n:List<String>" as LISTSTATUS

autonumber 7
-> CTRL: getStatusList()

autonumber 7.1
activate CTRL
    group Get Status List


        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getToDoList()
            activate REP

            REP --> CTRL : toDoList
            deactivate REP

        CTRL -> toDoList : getStatusList()
            activate toDoList

            toDoList -> LISTSTATUS** : create()
                    toDoList -> entry : getStatusList()
                        activate entry

                            loop for each status in the system
                                entry -> LISTSTATUS : add(status)
                                activate LISTSTATUS
                            end
                        LISTSTATUS --> entry : statusList
                        deactivate LISTSTATUS
                    entry --> toDoList : statusList
                    deactivate entry
        toDoList --> CTRL : statusList
        deactivate toDoList

    end

    autonumber 8
    <-- CTRL : statusList
deactivate CTRL


@enduml