@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":AgendaEntryMapper" as Mapper
participant "agendaEntryListDto\n:List<EntryDto>" as LISTENTRIESDTO
participant "agendaEntryDto\n:EntryDto" as DTO
participant "agendaEntries\n:List<AgendaEntries>" as AGENDAENTRIES

autonumber 32

 -> Mapper : toDto(listEntries)
autonumber 32.1
activate Mapper
    group Create a Copy of Entry List


            Mapper --> LISTENTRIESDTO** : create()
                loop for each entry in entryList
                    Mapper -> AGENDAENTRIES : get(i)
                        activate AGENDAENTRIES

                        AGENDAENTRIES --> Mapper : agendaEntry
                        deactivate AGENDAENTRIES
                    Mapper -> DTO : toDTOEntry(agendaEntry)
                        activate DTO

                        DTO --> Mapper : agendaEntryDto
                        deactivate DTO
                    Mapper -> LISTENTRIESDTO : add(agendaEntryDto)
                        activate LISTENTRIESDTO
                end


            LISTENTRIESDTO --> Mapper : agendaEntryListDto
             deactivate LISTENTRIESDTO

    end
    autonumber 33
    <-- Mapper : agendaEntryListDto
deactivate Mapper

@enduml