@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "taskRepository\n:TaskRepository" as taskRepository
participant "statusList\n:List<String>" as LISTSTATUS

autonumber 7
-> CTRL: getStatusList()

autonumber 7.1
activate CTRL
    group Register Vehicle


        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
            activate REP

            REP --> CTRL : taskRepository
            deactivate REP

        CTRL -> taskRepository : getStatusList()
            activate taskRepository

            taskRepository --> LISTSTATUS** : create()
                loop for each status in the system
                    taskRepository -> LISTSTATUS : add(status)
                        activate LISTSTATUS
                end
            LISTSTATUS --> taskRepository : statusList
            deactivate LISTSTATUS

        taskRepository --> CTRL : statusList
        deactivate taskRepository

    end

    autonumber 8
    <-- CTRL : statusList
deactivate CTRL


@enduml