@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "taskRepository\n:TaskRepository" as taskRepository
participant ":TaskMapper" as Mapper

autonumber 5

 -> CTRL : getTaskList(collaborator,dateI,dateF,typeStatus)
autonumber 5.1
activate CTRL
    group Get Task List

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
        activate REP

            REP --> CTRL: taskRepository
        deactivate REP

        CTRL -> taskRepository : getTaskList(collaborator,dateI,dateF,typeStatus)
        activate taskRepository

            taskRepository --> CTRL : taskList
        deactivate taskRepository

        CTRL -> Mapper : toDTO(taskList)
        activate Mapper

            Mapper --> CTRL : taskListDto
        deactivate Mapper

    end
deactivate CTRL

@enduml