@startuml
skinparam packageStyle folder
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0


package UI {
class "ListTaskSpaceUI" as UserInterface

}
package Controller {
class "ListTaskController" as CTRL {
    + create()
    + getCollaboratorThoughEmail(email)
    + getStatusList()
    + getTaskList(collaborator, dateI, dateF, typeStatus)
}
}
package Domain {
package Domain.Repository {
class "Repositories" as RepositorySingleton {
    - Repositories()
    + getInstance(): Repositories
    + getCollaboratorRepository(): CollaboratorRepository
    + getTaskRepository(): TaskRepository
}

class "CollaboratorRepository" as collaboratorRepository {
    + getCollaboratorThoughEmail(email)
}

class "TaskRepository" as taskRepository {
    - List<Task> taskList
    - List<String> statusList
    + getStatusList()
    + getTaskList(idNumber, dateI, dateF, typeStatus)
    + addTaskOfCollaborator(task)
}
}
package Domain.Mapper {
class "TaskMapper" as MapperDto {
    - List<Task> taskList
    + toDto(taskList)
    + addTask(task)
}
package Domain.Mapper.DTO {
class "TaskDto" as DataTransferObject {
    - Team team
    - List<vehicleList> vehicles
    - Date dateI
    - Date dateF
    - String status
    TaskDto(task)
}
}
}
}

UserInterface .> CTRL
CTRL ..> RepositorySingleton : repositories
RepositorySingleton -> RepositorySingleton : instance
CTRL .> taskRepository: taskRepository
RepositorySingleton "1" --> "1" taskRepository
RepositorySingleton "1" ..> "1" collaboratorRepository: collaboratorRepository
CTRL "1" --> "1" collaboratorRepository
CTRL "1" -> "1" MapperDto: taskList
MapperDto "1" --> "1" DataTransferObject: task
@enduml