@startuml
skinparam packageStyle folder
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

package UI {
class "ListTaskSpaceUI" as UserInterface
}

package Controller {
class "ListTaskController" as CTRL {
    + create()
    + getCollaboratorThoughEmail(email)
    + getStatusList()
    + getTaskList(collaborator, dateI, dateF, typeStatus)
}
}

package Domain {
package Model {
class Team {
    - List<Collaborator> members
    + inTeam(collaborator)
}
}
package Repository {

class "Repositories" as RepositorySingleton {
    - Repositories()
    + getInstance(): Repositories
    + getCollaboratorRepository(): CollaboratorRepository
    + getTaskRepository(): TaskRepository
    + getTeamRepository(): TeamRepository
    + getAgenda(): Agenda
}

class "CollaboratorRepository" as collaboratorRepository {
    + getCollaboratorThoughEmail(email)
}

class "TaskRepository" as taskRepository {
    - List<Task> taskList
    - List<String> statusList
    + getStatusList()
    + getTaskList(teamList, dateI, dateF, typeStatus)
    + addTaskOfCollaborator(task)
}

class "TeamRepository" as teamRepository {
    + getTeamsThoughCollaborator(collaborator): List<Team>
}

class "Agenda" as agenda {
    + getCollaboratorAgendaEntries(taskList): List<AgendaEntries>
}
}
package Mapper {
class "EntryMapper" as MapperDto {
    + toDTOList(listEntries): List<EntryDto>
    + toDTOEntry(entry): EntryDto
}
package DTO {
class "EntryDto" as DataTransferObject {
    - Team team
    - List<Vehicle> vehicles
    - Date dateI
    - Date dateF
    - String status
    + EntryDto(entry)
}
}
}
}

UserInterface ..> CTRL
CTRL ..> RepositorySingleton : repositories
RepositorySingleton --> RepositorySingleton : instance
CTRL ..> collaboratorRepository: getCollaboratorRepository
CTRL ..> taskRepository: getTaskRepository
CTRL ..> teamRepository: getTeamRepository
CTRL ..> agenda: getAgenda
CTRL ..> MapperDto: toDTOList
MapperDto "1" --> "*" DataTransferObject: entries
RepositorySingleton "1" ..> "1" collaboratorRepository: collaboratorRepository
RepositorySingleton "1" --> "1" taskRepository: taskRepository
RepositorySingleton "1" --> "1" teamRepository: teamRepository
RepositorySingleton "1" --> "1" agenda: agenda
teamRepository "1" --> "*" Team: collaborator
@enduml
