@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as Col
participant ":ListTaskSpaceUI" as UI
participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "taskRepository\n:TaskRepository" as taskRepository
participant ":TaskMapper" as Mapper

activate Col

    Col -> UI : requests to consult tasks assigned to him
    activate UI

        UI --> Col : asks to select the beginning and end date of the search
        deactivate UI

        Col -> UI : selects the beginning and end date
        activate UI

            UI --> Col : asks for confirmation
            deactivate UI

            Col -> UI : confirms that he wants to create the list
            activate UI

                UI -> CTRL** : create
                UI -> CTRL : getCollaboratorThoughEmail(email)
                activate CTRL

                    CTRL -> RepositorySingleton: getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> REP: getCollaboratorRepository
                    activate REP

                        REP --> CTRL: collaboratorRepository
                    deactivate REP

                    CTRL -> collaboratorRepository: getCollaboratorThoughEmail(email)
                    activate collaboratorRepository

                        collaboratorRepository -> collaboratorRepository: getCollaboratorThoughEmail(email)
                        activate collaboratorRepository

                            collaboratorRepository --> CTRL: collaborator
                        deactivate collaboratorRepository

                    deactivate collaboratorRepository
                    CTRL --> UI: collaborator
                deactivate CTRL

                UI --> Col : asks to select the type of status he wants to consult
                deactivate UI

                Col -> UI : Selects the type he wants to consult
                activate UI

                    UI --> Col : asks for confirmation
                    deactivate UI

                    Col -> UI : confirms that he wants to create the list
                    activate UI

                        UI -> CTRL : getTaskList(collaborator,dateI,dateF,typeStatus)
                        activate CTRL

                            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                                RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                            CTRL -> REP : getTaskRepository()
                            activate REP

                                REP --> CTRL: taskRepository
                            deactivate REP

                            CTRL -> taskRepository : getTaskList(collaborator,dateI,dateF,typeStatus)
                            activate taskRepository

                                taskRepository --> CTRL : taskList
                            deactivate taskRepository

                            CTRL -> Mapper : toDTO(taskList)
                            activate Mapper

                                Mapper --> CTRL : taskListDto
                            deactivate Mapper

                        CTRL --> UI: taskListDto
                    deactivate CTRL

                    UI --> Col: shows the LISTTASK
                deactivate UI

deactivate Col

@enduml