@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Col
participant ":ListTaskSpaceUI" as UI
participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "teamRepository\n:TeamRepository" as teamRepository

participant "taskRepository\n:TaskRepository" as taskRepository

participant "agenda\n:Agenda" as AGENDA
participant ":EntryMapper" as Mapper


activate Col

Col -> UI : requests to consult tasks assigned to him
    activate UI

    UI -> CTRL** : create
    UI -> CTRL : getCollaboratorByEmail(email)
        activate CTRL

        ref over CTRL
            Get Collaborator Though Email

        end
        CTRL --> UI : collaborator
        deactivate CTRL

    UI --> Col : asks to select the beginning and end date of the search
    deactivate UI

Col -> UI : selects the beginning and end date
    activate UI

    UI -> CTRL : getStatusList()
        activate CTRL

            ref over CTRL
                        Get Status List

            end

        CTRL --> UI : statusList
        deactivate CTRL

    UI --> Col : asks to select the type of status he wants to consult
    deactivate UI

Col -> UI : Selects the type he wants to consult
    activate UI

    UI --> Col : asks for confirmation
    deactivate UI

Col -> UI : confirms that he wants to create the list
    activate UI

    UI -> CTRL : getTaskList(collaborator,startDate,endDate,typeStatus)
        activate CTRL


        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTeamRepository()
            activate REP

            REP --> CTRL : teamRepository
            deactivate REP

        CTRL -> teamRepository : getTeamsThoughCollaborator(collaborator)
            activate teamRepository
                ref over teamRepository
                    Get Team List
                end
            teamRepository --> CTRL : teamList
            deactivate teamRepository

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
            activate REP

            REP --> CTRL : taskRepository
            deactivate REP

        CTRL -> taskRepository : getTaskList(teamList,typeStatus)
            activate taskRepository
                ref over taskRepository
                    Get Task List
                end
            taskRepository --> CTRL : taskList
        deactivate taskRepository


        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getAgenda()
            activate REP

            REP --> CTRL : Agenda
            deactivate REP

        CTRL -> AGENDA : getCollaboratorAgendaEntries(taskList,dateStart,dateEnd)
            activate AGENDA

                ref over AGENDA
                    Get Entry List

                end
        AGENDA --> CTRL : agendaEntryList
        deactivate AGENDA

        CTRL -> Mapper : toDTOList(agendaEntryList)
            activate Mapper
                ref over Mapper
                    Create a copy
                    of Entry List

                end

             Mapper --> CTRL : agendaEntryListDto
            deactivate Mapper

        CTRL --> UI : agendaEntryListDto
        deactivate CTRL

    UI --> Col : shows the LISTTASK
    deactivate UI

deactivate Col
@enduml
