@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Col
participant ":ListTaskSpaceUI" as UI
participant ":ListTaskController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "toDoList\n:ToDoList" as toDoList
participant "entry\n:Entry" as entry
participant "statusList\n:List<String>" as LISTSTATUS
participant "teamRepository\n:TeamRepository" as teamRepository
participant "teamList\n:List<Team>" as LISTTEAM
participant "team:Team" as TEAM
participant "taskRepository\n:TaskRepository" as taskRepository
participant "taskList\n:List<Task>" as LISTTASK
participant "agenda\n:Agenda" as AGENDA
participant ":EntryMapper" as Mapper
participant "listEntriesDto\n:List<EntryDto>" as LISTENTRIESDTO
participant "entryDto\n:EntryDto" as DTO
participant "agendaEntries\n:List<AgendaEntries>" as AGENDAENTRIES

activate Col

Col -> UI : requests to consult tasks assigned to him
    activate UI

    UI -> CTRL** : create
    UI -> CTRL : getCollaboratorByEmail(email)
        activate CTRL

            CTRL -> CTRL : getCollaboratorFromSession(email)
            activate CTRL
           CTRL -> _APP**: getInstance()
           activate _APP

                _APP -> CTRL: appSession
           deactivate _APP

           CTRL -> APP**: getCurrentSession()
           activate APP

                APP --> CTRL: currentSession
           deactivate APP

           CTRL -> SESSION**: getUserEmail()
           activate SESSION

                SESSION --> CTRL: email
           deactivate SESSION

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getCollaboratorRepository
            activate REP

            REP --> CTRL : collaboratorRepository
            deactivate REP

        CTRL -> collaboratorRepository : getCollaboratorByEmail(email)
            activate collaboratorRepository

            collaboratorRepository -> collaboratorRepository : getCollaboratorByEmail(email)
            activate collaboratorRepository

            collaboratorRepository --> CTRL : collaborator

                deactivate collaboratorRepository

            deactivate collaboratorRepository
        CTRL --> UI : collaborator
        deactivate CTRL

        deactivate CTRL
    UI --> Col : asks to select the beginning and end date of the search
    deactivate UI

Col -> UI : selects the beginning and end date
    activate UI

    UI -> CTRL : getStatusList()
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getToDoList()
            activate REP

            REP --> CTRL : toDoList
            deactivate REP

        CTRL -> toDoList : getStatusList()
            activate toDoList

            toDoList -> LISTSTATUS** : create()
                    toDoList -> entry : getStatusList()
                        activate entry

                            loop for each status in the system
                                entry -> LISTSTATUS : add(status)
                                activate LISTSTATUS
                            end
                        LISTSTATUS --> entry : statusList
                        deactivate LISTSTATUS
                    entry --> toDoList : statusList
                    deactivate entry
        toDoList --> CTRL : statusList
        deactivate toDoList

        CTRL --> UI : statusList
        deactivate CTRL

    UI --> Col : asks to select the type of status he wants to consult
    deactivate UI

Col -> UI : Selects the type he wants to consult
    activate UI

    UI --> Col : asks for confirmation
    deactivate UI

Col -> UI : confirms that he wants to create the list
    activate UI

    UI -> CTRL : getTaskList(collaborator,dateI,dateF,typeStatus)
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTeamRepository()
            activate REP

            REP --> CTRL : teamRepository
            deactivate REP

        CTRL -> teamRepository : getTeamsThoughCollaborator(collaborator)
            activate teamRepository

            teamRepository -> LISTTEAM** : create()
                loop for each team in the system
                    teamRepository -> TEAM** : validateCollaboratorTeam(collaborator,team)
                        activate TEAM
                        TEAM -> TEAM : inTeam = validateCollaboratorTeam(collaborator,team)
                        activate TEAM

                        TEAM --> teamRepository : inTeam
                        deactivate TEAM

                        deactivate TEAM
                    opt inTeam == true
                        teamRepository -> LISTTEAM : addTeamOfCollaborator(team)
                            activate LISTTEAM
                    end

                end
            LISTTEAM --> teamRepository : teamList
            deactivate LISTTEAM
            teamRepository --> CTRL : teamList
            deactivate teamRepository

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
            activate REP

            REP --> CTRL : taskRepository
            deactivate REP

        CTRL -> taskRepository : getTaskList(teamList,typeStatus)
            activate taskRepository

            taskRepository -> LISTTASK** : create()
                loop for each task in the system
                    loop for each team in the teamList
                    opt ((typeStatus() == task.getStatus()) && (team == task.getTeam()))
                        taskRepository -> LISTTASK : addTaskOfCollaborator(task)
                            activate LISTTASK
                    end

                    end

                end
            LISTTASK --> taskRepository : taskList
            deactivate LISTTASK

            taskRepository --> CTRL : taskList
        deactivate taskRepository

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getAgenda()
            activate REP

            REP --> CTRL : Agenda
            deactivate REP

        CTRL -> AGENDA : getCollaboratorAgendaEntries(taskList,dateI,dateF)
            activate AGENDA

            AGENDA --> AGENDAENTRIES** : create()
                loop for each task
                    loop for each agendaEntry
                        opt (agendaEntry.getTask() == task && agendaEntry.getDate() >= dateI && agendaEntry.getDate() <= dateF)
                            AGENDA -> AGENDAENTRIES : add(agendaEntry)
                                activate AGENDAENTRIES
                        end
                    end
                end
            AGENDAENTRIES --> AGENDA : listEntries
            deactivate AGENDAENTRIES
        AGENDA --> CTRL : listEntries
        deactivate AGENDA

        CTRL -> Mapper : toDTOList(listEntries)
            activate Mapper

            Mapper --> LISTENTRIESDTO** : create()
                loop for each entry in entryList
                    Mapper -> AGENDAENTRIES : get(i)
                        activate AGENDAENTRIES

                        AGENDAENTRIES --> Mapper : entry
                        deactivate AGENDAENTRIES
                    Mapper -> DTO : toDTOEntry(entry)
                        activate DTO

                        DTO --> Mapper : entryDto
                        deactivate DTO
                    Mapper -> LISTENTRIESDTO : add(taskDto)
                        activate LISTENTRIESDTO
                end


            LISTENTRIESDTO --> Mapper : listEntriesDto
             deactivate LISTENTRIESDTO

             Mapper --> CTRL : listEntriesDto
            deactivate Mapper

        CTRL --> UI : listEntriesDto
        deactivate CTRL

    UI --> Col : shows the LISTTASK
    deactivate UI

deactivate Col
@enduml
