@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ListTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "agenda\n:Agenda" as agenda
participant "agendaEntry\n:AgendaEntry" as agendaEntry
participant "statusList\n:List<String>" as LISTSTATUS

autonumber 7
-> CTRL: getStatusList()

autonumber 7.1
activate CTRL
    group Get Status List


        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

        CTRL -> REP : getAgenda()
            activate REP

            REP --> CTRL : agenda
            deactivate REP

        CTRL -> agenda : getStatusList()
            activate agenda

            agenda -> LISTSTATUS** : create()
                    agenda -> agendaEntry : getStatusList()
                        activate agendaEntry

                            loop for each status in the system
                                agendaEntry -> LISTSTATUS : add(status)
                                activate LISTSTATUS
                            end
                        LISTSTATUS --> agendaEntry : statusList
                        deactivate LISTSTATUS
                    agendaEntry --> agenda : statusList
                    deactivate agendaEntry
        agenda --> CTRL : statusList
        deactivate agenda

    end

    autonumber 8
    <-- CTRL : statusList
deactivate CTRL


@enduml