@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment\nFleet Manager\n(VFM)" as VFM
participant ":ListMaintenanceUI" as UI
participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "maintenanceRepository\n:MaintenanceRepository" as maintenanceRepository
participant "vehicleRepository\n:VehicleRepository" as vehicleRepository


activate VFM

        VFM -> UI : asks to list the vehicles that need maintenance

        activate UI

            UI --> VFM : asks for confirmation
        deactivate UI
            VFM -> UI : confirms that he wants to create the list
        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getMaintenanceList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()

                activate RepositorySingleton

                    RepositorySingleton --> CTRL : repositories
                deactivate RepositorySingleton

                CTRL -> REP : getVehicleRepository()
                activate REP

                    REP --> CTRL : vehicleRepository
                deactivate REP

                CTRL -> vehicleRepository : getVehicleList()
                activate vehicleRepository

                    vehicleRepository --> CTRL : vehicleList
                deactivate vehicleRepository
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> REP : getMaintenanceRepository()
                activate REP

                    REP --> CTRL: maintenanceRepository
                deactivate REP

                CTRL -> maintenanceRepository : getMaintenanceList(vehicleList)

                activate maintenanceRepository

                        maintenanceRepository --> CTRL : maintenanceList
                deactivate maintenanceRepository

            deactivate maintenanceRepository

            CTRL --> UI: maintenanceList
            deactivate CTRL
            UI --> VFM: shows the list
    deactivate UI

deactivate VFM



@enduml