@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'class Platform {
'  -description
'}

class Job {
    name
}

class Collaborator {
   name
   birthdate
   admission date
   address
   phone number
   email
   identification document
   number
}

class Competence {
    name
}

class SkillLevel {
    level
}

class AssignedCompetence {
    startDate
    endDate
}

class HRM {
   name
   birthdate
   admission date
   address
   phone number
   email
   identification document
   number
}

'class User {
'    name
'    email
'    password
'}


HRM "1" -- "1..*" Job : assigns >
Collaborator <|-- HRM
Competence "*" - "1..*" SkillLevel : has >
Collaborator "1" -- "*" AssignedCompetence : has >
Job "*" -- "*" AssignedCompetence : has >
AssignedCompetence "*" -- "1" Competence : is for >

@enduml
