@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false


'title Use Case Diagram Example

left to right direction

rectangle "System Actors" as actors {
    actor "Human Resources\nManager" as HRM
    actor "Vehicle and Equipment\nFleet Manager" as VFM
    actor "Green Spaces\nManager" as GSM
    actor "Software Quality\nAssessment Team \nManager" as QAM
    actor "Collaborator" as COLL
}


rectangle "Use Cases" as usecases{
    usecase "UC1 - Register Skills" as UC1
    HRM ----> UC1

    usecase "UC2 - Register a Job" as UC2
    HRM ----> UC2

    usecase "UC3 - Register a Collaborator" as UC3
    HRM ----> UC3

    usecase "UC4 - Assign one or more Skills to a Collaborator" as UC4
    HRM ----> UC4

    usecase "UC5 - Generate a Team Proposal" as UC5
    HRM ----> UC5

    usecase "UC6 - Register a Vehicle" as UC6
    VFM ----> UC6

    usecase "UC7 - Register a Vehicle’s Maintenance" as UC7
    VFM ----> UC7

    usecase "UC8 - List Vehicles that need Maintenance" as UC8
    VFM ----> UC8

    usecase "UC9 - Costs of water consumption" as UC9
    GSM ----> UC9

    usecase "UC10 - Find which piece of equipment is used each day" as UC10
    GSM ----> UC10

    usecase "UC11 - Collect data from user portal" as UC11
    GSM ----> UC11

    usecase "UC12 - Import .csv file" as UC12
    GSM ----> UC12

    usecase "UC13 - Algorithm that returns routes to be opened" as UC13
    GSM ----> UC13

    usecase "UC14 - Run tests for the inputs of variable size" as UC14
    QAM ----> UC14

    usecase "UC15 - The monthly cost associated with water consumption \nin each park is related to its size" as UC15
    GSM ----> UC15

    usecase "UC16 - Applying polynomial regression, determine the best \nline that fits the data" as UC16
    GSM ----> UC16

    usecase "UC17 - Put up evacuation signs and find the shortest \nroute from these different points to an Assembly Point" as UC17
    GSM ----> UC17

    usecase "UC18 - Put up signs to evacuate to one of several \nassembly points, so that these paths provide the shortest \nroutes to the nearest Assembly Point." as UC18
    GSM ----> UC18

    usecase "UC19 - Conclude about the worst-case time complexity \nof the procedures developed in US13, US17, and US18" as UC19
    QAM ----> UC19

    usecase "UC20 - Register a Green Space" as UC20
    GSM ----> UC20

    usecase "UC21 - Add a new entry to the To-Do List" as UC21
    GSM ----> UC21

    usecase "UC22 - Add a new entry in the Agenda" as UC22
    GSM ----> UC22

    usecase "UC23 - Assign a Team to an entry in the Agenda" as UC23
    GSM ----> UC23

    usecase "UC24 - Postpone an entry in the Agenda to a specific future date" as UC24
    GSM ----> UC24

    usecase "UC25 - Cancel an entry in the Agenda" as UC25
    GSM ----> UC25

    usecase "UC26 - Assign one or more vehicles to an entry in the Agenda" as UC26
    GSM ----> UC26

    usecase "UC27 - List all the green spaces managed by a collaborator" as UC27
    COLL ----> UC27

    usecase "UC28 - Consult the tasks assigned to a collaborator \nbetween two dates" as UC28
    COLL ----> UC28

    usecase "UC29 - Record the completion of a task" as UC29
    COLL ----> UC29
}


@enduml