@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "greenSpaceRepository\n:GreenSpaceRepository" as ORG
participant "greenSpace\n:GreenSpace" as GREENSPACE

autonumber 11
-> ORG: registerGreenSpace(name, type, area)

autonumber 11.1
activate ORG
    group Register Green Space

        ORG -> GREENSPACE**: registerGreenSpace(name, type, area)
        ORG -> ORG: addGreenSpace(greenSpace)

        activate ORG
            ORG -> ORG: validateGreenSpace(greenSpace)
            activate ORG

    end

    autonumber 12
    <-- ORG : greenSpace
deactivate ORG

@enduml
