@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository\n:GreenSpaceRepository" as greenSpaceRepository
participant "greenSpace\n:GreenSpace" as GREENSPACE

activate GSM

    GSM -> UI : Request to register a new green space

    activate UI

        UI --> GSM : Requests data (name, type, area)

        GSM -> UI : Provides requested data

        UI --> GSM : Shows all data and requests confirmation

        GSM -> UI : Confirms data

        UI -> CTRL : RegisterGreenSpace(name, type, area)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getGreenSpaceRepository()
            activate PLAT

                PLAT --> CTRL: greenSpaceRepository
            deactivate PLAT

            CTRL -> greenSpaceRepository : registerGreenSpace(name, type, area)
            activate greenSpaceRepository

                greenSpaceRepository -> GREENSPACE**: createGreenSpace(name, type, area)
                activate GREENSPACE
                    GREENSPACE --> greenSpaceRepository : greenSpace
                deactivate GREENSPACE

                greenSpaceRepository -> greenSpaceRepository: addGreenSpace(greenSpace)

                activate greenSpaceRepository
                    greenSpaceRepository -> greenSpaceRepository: validateGreenSpace(greenSpace)
                    activate greenSpaceRepository
                        greenSpaceRepository --> CTRL : greenSpace
                    deactivate greenSpaceRepository
                deactivate greenSpaceRepository

            deactivate greenSpaceRepository

        CTRL --> UI: Green space registration success
        deactivate CTRL

        UI --> GSM: Displays operation success
    deactivate UI

deactivate GSM

@enduml
