@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to postpone a entry to a future date
    activate System

loop
        System --> Employee : shows registered entries
    deactivate System

    Employee -> System : chooses entries to postpone and \nthe date to postpone them
    activate System

end
    System --> Employee : shows all data and requests confirmation
    deactivate System
   Employee -> System : confirms data
   activate System
        System -> Employee : displays operation success
    deactivate System

@enduml