@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class HRM {
    name
    birthdate
    admission date
    address
    phone number
    email
    identification document
    number
    collaborators
    vatNumber
}

class Skills {
    name
}
class Job {
    name
}


class Team {
    size
    members

}

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}



class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}


class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}

class VFM {
    name
    birthdate
    admission date
    address
    phone number
    email
    identification document
    number
}

class VehiclesCheckUp {
    plate id
}

class Competence {
    name
}

class SkillLevel {
    level
}

class AssignedCompetence {
    startDate
    endDate
}





HRM "1" -- "1..*" Job : assigns >
Competence "*" - "1..*" SkillLevel : has >
Collaborator "1" -- "*" AssignedCompetence : has >
Job "*" -- "*" AssignedCompetence : has >
AssignedCompetence "*" -- "1" Competence : is for >
VFM "1" --  "1..*" Vehicle: chooses >
VFM "1" --  "1..*" Vehicle: registers >
HRM "1" -- "1..*" Team : creates >
Collaborator "1" - "1..*" Skills: has >
Collaborator "1" -- "1" Job: has >
Team "1" -- "1..*" Collaborator: has >
GreenSpace "1" -- "1..*" Collaborator: contains >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
HRM "1" --> "*" Collaborator : registers
HRM "1" -- "1..*" Job : creates >
Collaborator <|-- HRM
HRM "1" -- "1..*" Skills: creates >
Collaborator <|-- VFM
VFM "1" -- "1..*" VehiclesCheckUp: lists >
@enduml