@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignTeamController" as CTRL
participant "agenda\n:Agenda" as AGENDA
participant "agendaEntry\n:AgendaEntry" as AGENDAENTRY
participant "team\n:Team" as TEAM

autonumber 13
-> CTRL: assignTeamToAgendaEntry(teamDto)

autonumber 13.1
activate CTRL
    group Assign Team

            CTRL -> CTRL : team = toDomain(teamDto)
            activate CTRL
            deactivate CTRL

            CTRL -> AGENDA : assignTeamToAgendaEntry(agendaEntry, team)
            activate AGENDA

                AGENDA -> AGENDAENTRY : assignTeam(team)
                activate AGENDAENTRY

                    AGENDAENTRY -> TEAM : assignAgendaEntry()
                    activate TEAM

                        TEAM -> TEAM : blockTeamAtATime()
                        activate TEAM
                        deactivate TEAM

                        TEAM --> AGENDAENTRY : operation success
                    deactivate TEAM

                    AGENDAENTRY --> AGENDA : operation success
                deactivate AGENDAENTRY

                AGENDA --> CTRL : operation success
            deactivate AGENDA


    end

    autonumber 14
    <-- CTRL : operation success
deactivate CTRL


@enduml