@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space\n Manager" as GSM
participant ":AssignTeamUI" as UI
participant ":AssignTeamController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "agenda\n:Agenda" as AGENDA
participant ":AgendaMapper" as AGENDAMAPPER
participant "agendaEntry\n:AgendaEntry" as AGENDAENTRY
participant "listEntries\n:List<agendaEntry>" as LISTENTRIES
participant "agendaDto\n:List<agendaEntriesDto>" as AGENDATDTO
participant "agendaEntryDto\n:AgendaDto" as AGENDAENTRYDTO

activate GSM


    GSM -> UI : asks to assign a team to an agenda entry
    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getAgendaEntries()
        activate CTRL

           CTRL -> Repositories: getInstance()
           activate Repositories

                Repositories --> CTRL: repositories
           deactivate Repositories

           CTRL -> REP: getAgenda()
           activate REP

                REP --> CTRL: Agenda
           deactivate REP

            CTRL -> AGENDA : getAgendaEntries()
            activate AGENDA

                    AGENDA --> LISTENTRIES** : create()
                    activate LISTENTRIES

                        loop for each agendaEntry
                            AGENDA -> AGENDAENTRY** : b = validateAgendaEntryToAssignTeam()

                            opt b == true
                            AGENDA -> LISTENTRIES : add(agendaEntry)
                            activate LISTENTRIES
                            deactivate LISTENTRIES
                            end

                        end

                        LISTENTRIES --> AGENDA : listEntries
                    deactivate LISTENTRIES


                AGENDA --> CTRL : listEntries
            deactivate AGENDA

            CTRL -> AGENDAMAPPER** : agendaEntriesToDto(listEntries)
            activate AGENDAMAPPER

                AGENDAMAPPER --> AGENDATDTO** : create()

                loop for each agendaEntry
                    AGENDAMAPPER -> LISTENTRIES : get(i)
                    activate LISTENTRIES

                    LISTENTRIES --> AGENDAMAPPER : agendaEntry
                    deactivate LISTENTRIES

                    AGENDAMAPPER -> AGENDAMAPPER : agendaEntryDto = toDTO(agendaEntry)
                    activate AGENDAMAPPER
                    deactivate AGENDAMAPPER

                    AGENDAMAPPER --> AGENDAENTRYDTO** : create()
                    activate AGENDAENTRYDTO

                    AGENDAENTRYDTO --> AGENDAMAPPER : agendaEntryDto
                    deactivate AGENDAENTRYDTO

                    AGENDAMAPPER -> AGENDATDTO : add(agendaEntryDto)
                    activate AGENDATDTO
                    deactivate AGENDATDTO

                end

                AGENDAMAPPER --> CTRL : agendaDto
            deactivate AGENDAMAPPER

            CTRL --> UI : agendaDto
        deactivate CTRL

        UI --> GSM : shows all the agenda entries created and \nasks you to select one
    deactivate UI

    GSM -> UI : choose an agenda entry
    activate UI

        UI --> GSM : shows all the teams available to carry out \nthat task and asks you to select one
    deactivate UI

    GSM -> UI : choose a team
    activate UI

        UI --> GSM : shows all data and requests confirmation
    deactivate UI

    GSM -> UI : confirms data
    activate UI

        UI --> GSM : displays operation success
    deactivate UI

deactivate GSM

@enduml