@startuml
'skinparam monochrome true
skinparam packageStyle folder
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

package "UI" #DDDDDD {

    class AssignTeamUI {
    }
}


package "Controller" #DDDDDD {

    class AssignTeamController {
        + AssignTeamController(agenda, teamRepository)
        + getAgendaEntries()
        + getValidTeams(agendaEntryDto)
        + toDomain(dto)
        + assignTeamToAgendaEntry(teamDto)

    }
}

package "Domain" #DDDDDD {

package "Repository" #DDDDDD {

    class Repositories {
        - Repositories()
        + getInstance() : Repositories
        + getAgenda()
        + getTeamRepository()

    }

    class Agenda {
        + getAgendaEntries()
        + assignTeamToAgendaEntry(agendaEntry, team)
    }

    class TeamRepository {
        + getValidTeams(agendaEntry)
    }

}

package "Mapper" #DDDDDD {

    class AgendaMapper {
        + agendaEntriesToDto(listEntries)
    }

    class TeamRepositoryMapper {
        + teamsToDto(listTeams)
    }
}

package "DTO" #DDDDDD {

    class AgendaEntryDto {
    }

    class TeamDto {
    }

}

    class Entry {
        - task : Task
        - greenSpace : GreenSpace
    }

    class AgendaEntry {
        - startDate : Date
        - endDate : Date
        - status : enum
        - team : Team
        + validateAgendaEntryToAssignTeam()
        + assignTeam(team)
    }

    class Team {
        - members : List<Collaborator>
        + validateTeamToBeAssignedToAnAgendaEntry(agendaEntry)
        + assignAgendaEntry()
        + blockTeamAtATime()
        + getMembers()
    }

    class Collaborator {
        - name : String
        - birthDate : Date
        - admissionDate : Date
        - address : String
        - mobile : String
        - email : String
        - taxPayerNumber : String
        - idDocumentType : enum
        - idDocumentNumber : String
        - job : Job
        - skillSet : List<Skill>
        - typeCollaboratorEmails : enum
        + Collaborator(name, birthDate, admissionDate, address, mobile, email, \ntaxPayerNumber, idDocumentType, idDocumentNumber, job, skillSet, typeCollaboratorEmails)
        + getEmail()
    }

    class EmailService {
        + sendEmail(email)
    }

    class GreenSpace {
        - name : String
        - type : enum
        - area : double
        - address : String
        + GreenSpace(name, type, area, address)
    }

    class Task {
        - description : String
        - team : Team
        - vehicles : List<Vehicle>
        - duration : Date
        + Task(description, team, vehicles, duration)
    }

    interface EmailModule {
        + send(email)
    }

    class EmailModuleAdapter1 {
        + send(email)
    }

    class EmailModuleAdapter2 {
        + send(email)
    }

}

AssignTeamUI ..> AssignTeamController
AssignTeamController ..> Repositories : repositories
Repositories --> Repositories : instance
AssignTeamController ..> Agenda : agenda
AssignTeamController ..> TeamRepository : teamRepository

AssignTeamController ..> AgendaMapper : agendaEntriesDto
AssignTeamController ..> TeamRepositoryMapper : teamsDto
AssignTeamController ..> Agenda : listEntries
AssignTeamController ..> TeamRepository : listTeams

Repositories --> "1" Agenda
Repositories --> "1" TeamRepository

AgendaEntryDto ..> AgendaMapper : agendaEntryDto
TeamDto ..> TeamRepositoryMapper : teamDto

Entry --|> AgendaEntry : extends
AgendaEntry --o Team : has
Team --o Collaborator : has
AgendaEntry --o Task : has
AgendaEntry --o GreenSpace : has

Collaborator --o EmailService : has
AssignTeamController ..> EmailService

EmailModule <|.. EmailModuleAdapter1
EmailModule <|.. EmailModuleAdapter2
AssignTeamController ..> EmailModule : makes use of

@enduml