@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class HRM {

 }

class Team {
    size
    members
}

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class Organization{
    name
    address
}

class Skill{
    name
}

class Job{
    name
}

HRM "1" -- "*" Team : creates >
Team "1" -- "1..*" Collaborator: has >
Collaborator "1" -- "*" Skill: has >
Collaborator "1" -- "*" Job: has >
Organization "1" -- "1..*" Collaborator: works for <
Organization "1" -- "*" Skill: has >
Organization "1" -- "*" Job: has >
@enduml