@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "maintenanceRepository\n:MaintenanceRepository" as MAINREP
participant "maintenance\n:Maintenance" as MAINTENANCE

autonumber 19
-> MAINREP: registerVehicleMaintenance(vehicleList, date)

autonumber 19.1
activate MAINREP
    group Register Maintenance

        MAINREP -> MAINTENANCE**: registerVehicleMaintenance(vehicleList, date)
        MAINREP -> MAINREP: addVehicleMaintenance (maintenance)

        activate MAINREP
            MAINREP -> MAINREP: validateMaintenance(maintenance)
            activate MAINREP
            deactivate MAINREP

        deactivate MAINREP
        end
    autonumber 20
    <-- MAINREP : maintenance
        deactivate MAINREP



@enduml