@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Employee {
    - name
    - email
    - position
    - phone
}

class Organization {
    - String name
    - String vatNumber
    - String website
    - String phone
    - String email

    + anyEmployeeHasEmail(email)
    + Organization(name, vatNumber, webSite, phone, email, postalAddress, manager)
    - getEmployeeByEmail(email)

}

class TaskCategoryRepository {
    + getTaskCategoryByDescription(description)
}

class OrganizationRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getTaskCategoryRepository()
    + getOrganizationRepository()
}

class RegisterVehicleController {
    + RegisterVehicleController(organizationRepository, taskCategoryRepository)
    + registerVehicle(plateNumber, brand, model, type, tare, grossWeight, currentKms, registrationDate, acquisitionDate, serviceFrequency)
}

note bottom of TaskCategoryRepository
    - used for displaying
    the category list
end note

class RegisterVehicleUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

RegisterVehicleUI .> RegisterVehicleController

RegisterVehicleController .> Repositories : repositories

Repositories -> "1" TaskCategoryRepository

RegisterVehicleController ..> OrganizationRepository : organizationRepository
RegisterVehicleController ..> TaskCategoryRepository : TaskCategoryRepository

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

RegisterVehicleController ..> "1" Organization : organization
RegisterVehicleController ..> ApplicationSession
RegisterVehicleController ..> UserSession
Organization --> "*" Employee : employs

@enduml