@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":RegisterVehicleMaintenanceUI" as UI
participant ":RegisterVehicleMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as VREP
participant "vehicleMaintenanceRepository\n:VehicleMaintenanceRepository" as RegisterVehicleRepository
participant "maintenance\n:Maintenance" as MAINTENANCE

activate ADM

        ADM -> UI : asks to register a vehicle maintenance

        activate UI
        UI -> CTRL : getVehicleList()
            activate CTRL
            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton -> CTRL : repositories
            deactivate RepositorySingleton
            CTRL -> PLAT : getVehicleRepository()
            activate PLAT
            PLAT -> CTRL : vehicleRepository
            deactivate PLAT

            CTRL -> VREP : getVehicleList()
            activate VREP
            VREP -> CTRL : vehicleList
            deactivate VREP

            CTRL -> UI : vehicleList
            deactivate CTRL

            loop
            UI --> ADM : shows list of registered vehicles
            deactivate UI

            ADM -> UI : chooses vehicle for maintenance
            activate UI
            end
            UI --> ADM : shows all data and requests confirmation
            deactivate UI
            ADM -> UI : confirms data
            activate UI
            UI -> CTRL : registerVehicleMaintenance(vehicleList, date)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getRegisterVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: registerVehicleRepository
                deactivate PLAT

                CTRL -> RegisterVehicleRepository : registerVehicleMaintenance(vehicleList, date)
                activate RegisterVehicleRepository

                RegisterVehicleRepository -> MAINTENANCE**: registerVehicleMaintenance(vehicleList, date)

                loop
                RegisterVehicleRepository -> RegisterVehicleRepository: addVehicle (vehicle)

                 activate RegisterVehicleRepository
                     RegisterVehicleRepository -> RegisterVehicleRepository: validateVehicle(vehicle)
                 end
                 deactivate RegisterVehicleRepository
                                RegisterVehicleRepository --> CTRL : maintenance
                            deactivate RegisterVehicleRepository


            CTRL --> UI: maintenance
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml