@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : requests to register a collaborator
    activate System

        System --> HRM : prompts for collaborator's name
    deactivate System

    HRM -> System : inputs collaborator's name
    activate System

        System --> HRM : prompts for contact information
    deactivate System

    HRM -> System : inputs contact information
    activate System

        System --> HRM : prompts for job position
    deactivate System

    HRM -> System : selects job position
    activate System

        System --> HRM : prompts for required skills
    deactivate System

    HRM -> System : selects required skills
    activate System

        System --> HRM : prompts for sector of activity
    deactivate System

    HRM -> System : selects sector of activity
    activate System

        System --> HRM : presents data for confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

        System --> HRM : displays operation success
    deactivate System

@enduml
