@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AddAgendaEntryController" as CTRL
participant "agenda\n:Agenda" as AGENDA

autonumber 15
-> CTRL: addAgendaEntry(agendaEntry)

autonumber 15.1
activate CTRL
    group Add Agenda Entry

            CTRL -> AGENDA : addAgendaEntry(agendaEntry)
            activate AGENDA

            AGENDA -> AGENDA : validateEntry()
            activate AGENDA

            deactivate AGENDA

            AGENDA --> CTRL : operation success
            deactivate AGENDA


    end

    autonumber 16
    <-- CTRL : operation success
deactivate CTRL


@enduml