@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces\n Manager" as GSM
participant ":AddAgendaEntryUI" as UI
participant ":AddAgendaEntryController" as CTRL

activate GSM

    GSM -> UI : asks to add a new entry to the agenda
    activate UI

        UI --> GSM : asks to choose the green space \nfor which want to add the entry
    deactivate UI

    GSM -> UI : select the desired green space
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getToDoListEntries()
        activate CTRL

           ref over CTRL
           Get Green Space and your To-Do List
           entries with DTO

           end

            CTRL --> UI : toDoListDto
        deactivate CTRL

        UI --> GSM: shows all the tasks registered in the \nto-do list of the chosen green space \nand asks to select the one want to add
    deactivate UI

    GSM -> UI: select the desired task and its start and\n end date
    activate UI

        UI -> CTRL : getTask(toDoListEntryDto)
        activate CTRL

            ref over CTRL
            Get Task

            end

            CTRL --> UI : task
        deactivate CTRL

        UI -> CTRL : createAgendaEntry(task, greenSpace, startDate, endDate)
        activate CTRL

            ref over CTRL
            Create Agenda Entry

            end

            CTRL --> UI : agendaEntry
            deactivate CTRL

        UI --> GSM: shows all data and requests confirmation
    deactivate UI

    GSM -> UI: confirms data
    activate UI

        UI -> CTRL : addAgendaEntry(agendaEntry)
        activate CTRL

            ref over CTRL
            Add Agenda Entry

            end

            CTRL --> UI : operation success
        deactivate CTRL

        UI --> GSM: displays operation success
    deactivate UI

deactivate GSM

@enduml