@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AddAgendaEntryController" as CTRL
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "task\n:Task" as TASK

autonumber 13
-> CTRL: getTask(toDoListEntryDto)

autonumber 13.1
activate CTRL
    group Get Task

             CTRL -> CTRL : toDoListEntry = toDomain(toDoListEntryDto)
             activate CTRL
             deactivate CTRL

            CTRL -> TODOLISTENTRY** : getTask(toDoListEntry)
            activate TODOLISTENTRY

                    TODOLISTENTRY -> TASK** : getTask()
                    activate TASK

                        TASK --> TODOLISTENTRY : task
                    deactivate TASK

                TODOLISTENTRY --> CTRL : task
            deactivate TODOLISTENTRY

    end

    autonumber 14
    <-- CTRL : task
deactivate CTRL


@enduml