@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AddAgendaEntryController" as CTRL
participant "toDoList\n:toDoList" as TODOLIST
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "task\n:Task" as TASK

autonumber 7
-> CTRL: getTask(toDoListEntryDto)

autonumber 7.1
activate CTRL
    group Get Task

             CTRL -> CTRL : toDoListEntry = toDomain(toDoListEntryDto)
             activate CTRL
             deactivate CTRL

            CTRL -> TODOLIST : getTask(toDoListEntry)
            activate TODOLIST

                TODOLIST -> TODOLISTENTRY** : getTask()
                activate TODOLISTENTRY

                    TODOLISTENTRY -> TASK** : getTask()
                    activate TASK

                        TASK --> TODOLISTENTRY : task
                    deactivate TASK

                    TODOLISTENTRY --> TODOLIST : task
                deactivate TODOLISTENTRY

                TODOLIST --> CTRL : task
            deactivate TODOLIST

    end

    autonumber 8
    <-- CTRL : task
deactivate CTRL


@enduml