@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces\n Manager" as GSM
participant ":AddAgendaEntryUI" as UI
participant ":AddAgendaEntryController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "greenSpaceRepository\n:GreenSpaceRepository" as GREENSPACEREPOSITORY
participant ":GreenSpaceRepositoryMapper" as GREENSPACEREPOSITORYMAPPER
participant "listGreenSpaces\n:List<GreenSpace>" as LISTGREENSPACES
participant "listGreenSpacesDto\n:List<GreenSpaceDto>" as LISTGREENSPACESDTO
participant "greenSpaceDto\n:GreenSpaceDto" as GREENSPACEDTO
participant "greenSpace\n: GreenSpace" as GREENSPACE
participant "toDoList\n:toDoList" as TODOLIST
participant ":ToDoListMapper" as TODOLISTMAPPER
participant "listEntries\n:List<ToDoListEntry>" as LISTENTRIES
participant "toDoListDto\n:List<ToDoListEntriesDto>" as TODOLISTDTO
participant "toDoListEntryDto\n:ToDoListDto" as TODOLISTENTRYDTO
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "task\n:Task" as TASK
participant "agenda\n:Agenda" as AGENDA
participant "agendaEntry\n:AgendaEntry" as AGENDAENTRY

activate GSM

    GSM -> UI : asks to add a new entry to the agenda
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getListGreenSpaces()
        activate CTRL

           CTRL -> Repositories**: getInstance()
           activate Repositories

                Repositories --> CTRL: repositories
           deactivate Repositories

           CTRL -> REP**: getGreenSpaceRepository()
           activate REP

                 REP --> CTRL: greenSpaceRepository
           deactivate REP

            CTRL -> GREENSPACEREPOSITORY** : getListGreenSpaces()
            activate GREENSPACEREPOSITORY

                    GREENSPACEREPOSITORY --> LISTGREENSPACES** : create()
                    activate LISTGREENSPACES

                        loop for each greenSpace
                            GREENSPACEREPOSITORY -> LISTGREENSPACES : add(greenSpace)
                            activate LISTGREENSPACES
                            deactivate LISTGREENSPACES
                        end

                        LISTGREENSPACES --> GREENSPACEREPOSITORY : listGreenSpaces
                    deactivate LISTGREENSPACES


                GREENSPACEREPOSITORY --> CTRL : listGreenSpaces
            deactivate GREENSPACEREPOSITORY

            CTRL -> GREENSPACEREPOSITORYMAPPER** : listGreenSpacesToDto(listGreenSpaces)
            activate GREENSPACEREPOSITORYMAPPER

                GREENSPACEREPOSITORYMAPPER --> LISTGREENSPACESDTO** : create()

                loop for each greenSpace
                    GREENSPACEREPOSITORYMAPPER -> LISTGREENSPACES : get(i)
                    activate LISTGREENSPACES

                    LISTGREENSPACES --> GREENSPACEREPOSITORYMAPPER : greenSpace
                    deactivate LISTGREENSPACES

                    GREENSPACEREPOSITORYMAPPER -> GREENSPACEREPOSITORYMAPPER : greenSpaceDto = toDTO(greenSpace)
                    activate GREENSPACEREPOSITORYMAPPER
                    deactivate GREENSPACEREPOSITORYMAPPER

                    GREENSPACEREPOSITORYMAPPER --> GREENSPACEDTO** : create()
                    activate GREENSPACEDTO

                    GREENSPACEDTO --> GREENSPACEREPOSITORYMAPPER : greenSpaceDto
                    deactivate GREENSPACEDTO

                    GREENSPACEREPOSITORYMAPPER -> LISTGREENSPACESDTO : add(greenSpaceDto)
                    activate LISTGREENSPACESDTO
                    deactivate LISTGREENSPACESDTO

                end

                GREENSPACEREPOSITORYMAPPER --> CTRL : listGreenSpacesDto
            deactivate GREENSPACEREPOSITORYMAPPER

            CTRL --> UI : listGreenSpacesDto
        deactivate CTRL

        UI --> GSM : asks to choose the green space \nfor which want to add the entry
    deactivate UI

    GSM -> UI : select the desired green space
    activate UI

        UI -> CTRL : getToDoListEntries(greenSpaceDto)
        activate CTRL

           CTRL -> CTRL : greenSpace = toDomain(greenSpaceDto)
           activate CTRL
           deactivate CTRL

           CTRL -> GREENSPACE**: getToDoList()
           activate GREENSPACE

                GREENSPACE --> CTRL: toDoList
           deactivate GREENSPACE

            CTRL -> TODOLIST** : getToDoListEntries()
            activate TODOLIST

                    TODOLIST --> LISTENTRIES** : create()
                    activate LISTENTRIES

                        loop for each toDoListEntry
                            TODOLIST -> LISTENTRIES : add(toDoListEntry)
                            activate LISTENTRIES
                            deactivate LISTENTRIES
                        end

                        LISTENTRIES --> TODOLIST : listEntries
                    deactivate LISTENTRIES


                TODOLIST --> CTRL : listEntries
            deactivate TODOLIST

            CTRL -> TODOLISTMAPPER** : toDoListEntriesToDto(listEntries)
            activate TODOLISTMAPPER

                TODOLISTMAPPER --> TODOLISTDTO** : create()

                loop for each toDoListEntry
                    TODOLISTMAPPER -> LISTENTRIES : get(i)
                    activate LISTENTRIES

                    LISTENTRIES --> TODOLISTMAPPER : toDoListEntry
                    deactivate LISTENTRIES

                    TODOLISTMAPPER -> TODOLISTMAPPER : toDoListEntryDto = toDTO(toDoListEntry)
                    activate TODOLISTMAPPER
                    deactivate TODOLISTMAPPER

                    TODOLISTMAPPER --> TODOLISTENTRYDTO** : create()
                    activate TODOLISTENTRYDTO

                    TODOLISTENTRYDTO --> TODOLISTMAPPER : toDoListEntryDto
                    deactivate TODOLISTENTRYDTO

                    TODOLISTMAPPER -> TODOLISTDTO : add(toDoListEntryDto)
                    activate TODOLISTDTO
                    deactivate TODOLISTDTO

                end

                TODOLISTMAPPER --> CTRL : toDoListDto
            deactivate TODOLISTMAPPER

            CTRL --> UI : toDoListDto
        deactivate CTRL

        UI --> GSM: shows all the tasks registered in the \nto-do list of the chosen green space \nand asks to select the one want to add
    deactivate UI

    GSM -> UI: select the desired task and its start and\n end date
    activate UI

        UI -> CTRL : getTask(toDoListEntryDto)
        activate CTRL

            CTRL -> CTRL : toDoListEntry = toDomain(toDoListEntryDto)
            activate CTRL
            deactivate CTRL

            CTRL -> TODOLIST : getTask(toDoListEntry)
            activate TODOLIST

                TODOLIST -> TODOLISTENTRY** : getTask()
                activate TODOLISTENTRY

                    TODOLISTENTRY -> TASK** : getTask()
                    activate TASK

                        TASK --> TODOLISTENTRY : task
                    deactivate TASK

                    TODOLISTENTRY --> TODOLIST : task
                deactivate TODOLISTENTRY

                TODOLIST --> CTRL : task
            deactivate TODOLIST

            CTRL --> UI : task
        deactivate CTRL

        UI -> CTRL : createAgendaEntry(task, greenSpace, startDate, endDate)
        activate CTRL

            CTRL -> Repositories: getInstance()
            activate Repositories

                Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getAgenda()
            activate REP

                REP --> CTRL: agenda
            deactivate REP

            CTRL -> AGENDA** : createAgendaEntry(task, greenSpace, startDate, endDate)
            activate AGENDA

                AGENDA -> AGENDAENTRY** : createEntry(task, greenSpace, startDate, endDate)
                activate AGENDAENTRY

                AGENDAENTRY -> AGENDAENTRY : b = validateEntry()
                activate AGENDAENTRY
                deactivate AGENDAENTRY

                opt b == true
                AGENDAENTRY -> AGENDAENTRY : taskSchedule()
                activate AGENDAENTRY

                    AGENDAENTRY --> AGENDA : ok
                deactivate AGENDAENTRY

                deactivate AGENDAENTRY
                end

                AGENDA --> CTRL : agendaEntry
                deactivate AGENDA

            CTRL --> UI : agendaEntry
            deactivate CTRL

        UI --> GSM: shows all data and requests confirmation
    deactivate UI

    GSM -> UI: confirms data
    activate UI

        UI -> CTRL : addAgendaEntry(agendaEntry)
        activate CTRL

            CTRL -> AGENDA : addAgendaEntry(agendaEntry)
            activate AGENDA

            AGENDA -> AGENDA : validateEntry()
            activate AGENDA

            deactivate AGENDA

            AGENDA --> CTRL : operation success
            deactivate AGENDA

            CTRL --> UI : operation success
        deactivate CTRL

        UI --> GSM: displays operation success
    deactivate UI

deactivate GSM

@enduml