@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AddAgendaEntryController" as CTRL
participant "toDoList\n:toDoList" as TODOLIST
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "greenSpace\n: GreenSpace" as GREENSPACE

autonumber 9
-> CTRL: getGreenSpace(toDoListEntry)

autonumber 9.1
activate CTRL
    group Get Green Space

            CTRL -> TODOLIST : getGreenSpace(toDoListEntry)
            activate TODOLIST

                TODOLIST -> TODOLISTENTRY** : getGreenSpace()
                activate TODOLISTENTRY

                    TODOLISTENTRY -> GREENSPACE** : getGreenSpace()
                    activate GREENSPACE

                        GREENSPACE --> TODOLISTENTRY : greenSpace
                    deactivate GREENSPACE

                    TODOLISTENTRY --> TODOLIST : greenSpace
                deactivate TODOLISTENTRY

                TODOLIST --> CTRL : greenSpace
            deactivate TODOLIST

    end

    autonumber 10
    <-- CTRL : greenSpace
deactivate CTRL


@enduml