@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AddAgendaEntryController" as CTRL
participant "greenSpace\n: GreenSpace" as GREENSPACE
participant "toDoList\n:toDoList" as TODOLIST
participant ":ToDoListMapper" as TODOLISTMAPPER
participant "listEntries\n:List<ToDoListEntry>" as LISTENTRIES
participant "toDoListDto\n:List<ToDoListEntriesDto>" as TODOLISTDTO
participant "toDoListEntryDto\n:ToDoListDto" as TODOLISTENTRYDTO

autonumber 7
-> CTRL: getToDoListEntries(greenSpaceDto)

autonumber 7.1
activate CTRL
    group Get To-Do List entries with DTO

           CTRL -> CTRL : greenSpace = toDomain(greenSpaceDto)
           activate CTRL
           deactivate CTRL

           CTRL -> GREENSPACE**: getToDoList()
           activate GREENSPACE

                GREENSPACE --> CTRL: toDoList
           deactivate GREENSPACE

            CTRL -> TODOLIST** : getToDoListEntries()
            activate TODOLIST

                    TODOLIST --> LISTENTRIES** : create()
                    activate LISTENTRIES

                        loop for each toDoListEntry
                            TODOLIST -> LISTENTRIES : add(toDoListEntry)
                            activate LISTENTRIES
                            deactivate LISTENTRIES
                        end

                        LISTENTRIES --> TODOLIST : listEntries
                    deactivate LISTENTRIES


                TODOLIST --> CTRL : listEntries
            deactivate TODOLIST

            CTRL -> TODOLISTMAPPER** : toDoListEntriesToDto(listEntries)
            activate TODOLISTMAPPER

                TODOLISTMAPPER --> TODOLISTDTO** : create()

                loop for each toDoListEntry
                    TODOLISTMAPPER -> LISTENTRIES : get(i)
                    activate LISTENTRIES

                    LISTENTRIES --> TODOLISTMAPPER : toDoListEntry
                    deactivate LISTENTRIES

                    TODOLISTMAPPER -> TODOLISTMAPPER : toDoListEntryDto = toDTO(toDoListEntry)
                    activate TODOLISTMAPPER
                    deactivate TODOLISTMAPPER

                    TODOLISTMAPPER --> TODOLISTENTRYDTO** : create()
                    activate TODOLISTENTRYDTO

                    TODOLISTENTRYDTO --> TODOLISTMAPPER : toDoListEntryDto
                    deactivate TODOLISTENTRYDTO

                    TODOLISTMAPPER -> TODOLISTDTO : add(toDoListEntryDto)
                    activate TODOLISTDTO
                    deactivate TODOLISTDTO

                end

                TODOLISTMAPPER --> CTRL : toDoListDto
            deactivate TODOLISTMAPPER

    end

    autonumber 8
    <-- CTRL : toDoListDto
deactivate CTRL


@enduml