@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces\n Manager" as GSM
participant ":AddAgendaEntryUI" as UI
participant ":AddAgendaEntryController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "toDoList\n:toDoList" as TODOLIST
participant ":ToDoListMapper" as TODOLISTMAPPER
participant "listEntries\n:List<ToDoListEntry>" as LISTENTRIES
participant "toDoListDto\n:List<toDoListDto>" as TODOLISTDTO
participant "objDto\n:ToDoListEntryDto" as TODOLISTENTRYDTO

activate GSM

    GSM -> UI : asks to add a new entry to the agenda
    activate UI

        UI -> CTRL** : add

        UI -> CTRL : getToDoListEntries()
        activate CTRL

           CTRL -> Repositories: getInstance()
           activate Repositories

                Repositories --> CTRL: repositories
           deactivate Repositories

           CTRL -> REP: getToDoList()
           activate REP

                REP --> CTRL: toDoList
           deactivate REP

            CTRL -> TODOLIST : getToDoListEntries()
            activate TODOLIST

                    TODOLIST --> LISTENTRIES** : create()
                    activate LISTENTRIES

                        loop for each toDoListEntry
                            TODOLIST -> LISTENTRIES : add(toDoListEntry)
                            activate LISTENTRIES
                            deactivate LISTENTRIES
                        end

                        LISTENTRIES --> TODOLIST : listEntries
                    deactivate LISTENTRIES


                TODOLIST --> CTRL : listEntries
            deactivate TODOLIST

            CTRL -> TODOLISTMAPPER : toDoListEntriesToDto(listEntries)
            activate TODOLISTMAPPER

                TODOLISTMAPPER --> TODOLISTDTO** : create()

                loop for each toDoListEntry
                    TODOLISTMAPPER -> LISTENTRIES : obj = get(i)
                    activate LISTENTRIES
                    deactivate LISTENTRIES

                    TODOLISTMAPPER -> TODOLISTMAPPER : objDto = toDTO(obj)
                    activate TODOLISTMAPPER
                    deactivate TODOLISTMAPPER

                    TODOLISTMAPPER --> TODOLISTENTRYDTO** : create()

                    TODOLISTMAPPER -> TODOLISTDTO : add(objDto)
                    activate TODOLISTDTO
                    deactivate TODOLISTDTO

                end

                TODOLISTMAPPER --> CTRL : toDoListDto
            deactivate TODOLISTMAPPER

            CTRL --> UI : toDoListDto
        deactivate CTRL

        UI --> GSM: shows all the tasks registered in the \nTo-Do List and asks you to select the \none you want to add
    deactivate UI

    GSM -> UI: select the desired task
    activate UI

        UI --> GSM: shows all data and requests confirmation
    deactivate UI

    GSM -> UI: confirms data
    activate UI

        UI --> GSM: displays operation success
    deactivate UI

deactivate GSM

@enduml