@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space\nManager" as GSM
participant ":RegisterToDoListEntryUI" as UI
participant ":RegisterToDoListEntryController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "greenSpaceRepository\n:GreenSpaceRepository" as GREENSPACEREPO
participant "toDoListRepository\n:ToDoListRepository" as TODOLISTREPO
participant "listGreenSpaces\n:List<GreenSpace>" as LISTGREENSPACES
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY

activate GSM

    GSM -> UI : Request to add a new entry to the To-Do List
    activate UI

        UI -> CTRL** : Create

        UI -> CTRL : getGreenSpaces()
        activate CTRL

            CTRL -> Repositories: getInstance()
            activate Repositories

                Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getGreenSpaceRepository()
            activate REP

                REP --> CTRL: greenSpaceRepository
            deactivate REP

            CTRL -> GREENSPACEREPO: getGreenSpaces()
            activate GREENSPACEREPO

                GREENSPACEREPO --> CTRL: listGreenSpaces
            deactivate GREENSPACEREPO

            CTRL --> UI: listGreenSpaces
        deactivate CTRL

        UI --> GSM: Display the list of green spaces
    deactivate UI

    GSM -> UI: Choose green space
    activate UI

        UI -> CTRL: getTaskDetails(greenSpace)
        activate CTRL

            CTRL -> TODOLISTENTRY**: create(greenSpace)
            activate TODOLISTENTRY

            TODOLISTENTRY --> CTRL: toDoListEntry
            deactivate TODOLISTENTRY

            CTRL --> UI: Prompt for task details (description, urgency, duration)
        deactivate CTRL

        UI --> GSM: Prompt for task details (description, urgency, duration)
    deactivate UI

    GSM -> UI: Provide task details
    activate UI

        UI -> CTRL: createToDoListEntry(toDoListEntry, taskDetails, urgency, duration)
        activate CTRL

            CTRL -> TODOLISTREPO: addToDoListEntry(toDoListEntry)
            activate TODOLISTREPO

                TODOLISTREPO -> TODOLISTREPO: validateEntry()
                activate TODOLISTREPO
                deactivate TODOLISTREPO

                TODOLISTREPO --> CTRL: operation success
            deactivate TODOLISTREPO

            CTRL --> UI: operation success
        deactivate CTRL

        UI --> GSM: Display operation success
    deactivate UI

deactivate GSM

@enduml
