@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space\nManager" as GSM
participant ":AddToDoListEntryUI" as UI
participant ":AddToDoListEntryController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant Repositories
participant "repositories\n:Repositories" as REP
participant "greenSpaceRepository\n:GreenSpaceRepository" as GREENSPACEREPOSITORY
participant ":GreenSpaceRepositoryMapper" as GREENSPACEREPOSITORYMAPPER
participant "listGreenSpaces\n:List<GreenSpace>" as LISTGREENSPACES
participant "listGreenSpacesDto\n:List<GreenSpaceDto>" as LISTGREENSPACESDTO
participant "greenSpaceDto\n:GreenSpaceDto" as GREENSPACEDTO
participant "greenSpace\n:GreenSpace" as GREENSPACE
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY

activate GSM

    GSM -> UI : Request to add a new entry to the To-Do List
    activate UI

        UI -> CTRL** : Create

        UI -> CTRL : getListGreenSpaces()
        activate CTRL

            CTRL -> _APP**: getInstance()
            activate _APP

                _APP -> CTRL: appSession
            deactivate _APP

            CTRL -> APP**: getCurrentSession()
            activate APP

                APP --> CTRL: currentSession
            deactivate APP

            CTRL -> SESSION**: getUserEmail()
            activate SESSION

                SESSION --> CTRL: email
            deactivate SESSION

            CTRL -> Repositories**: getInstance()
            activate Repositories

                Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getGreenSpaceRepository()
            activate REP

                REP --> CTRL: greenSpaceRepository
            deactivate REP

            CTRL -> GREENSPACEREPOSITORY** : getListGreenSpacesManagedByGsm(greenSpaceManager)
            activate GREENSPACEREPOSITORY

                GREENSPACEREPOSITORY --> CTRL: listGreenSpaces
            deactivate GREENSPACEREPOSITORY

            CTRL -> GREENSPACEREPOSITORYMAPPER** : listGreenSpacesToDto(listGreenSpaces)
            activate GREENSPACEREPOSITORYMAPPER

                GREENSPACEREPOSITORYMAPPER --> CTRL : listGreenSpacesDto
            deactivate GREENSPACEREPOSITORYMAPPER

            CTRL --> UI : listGreenSpacesDto
        deactivate CTRL

        UI --> GSM : Displays the list of green spaces
    deactivate UI

    GSM -> UI : Select the desired green space
    activate UI

        UI -> CTRL : createToDoListEntry(greenSpaceDto, taskDetails, urgency, duration)
        activate CTRL

            CTRL -> GREENSPACEREPOSITORYMAPPER : greenSpaceDtoToDomain(greenSpaceDto)
            activate GREENSPACEREPOSITORYMAPPER

                GREENSPACEREPOSITORYMAPPER --> CTRL : greenSpace
            deactivate GREENSPACEREPOSITORYMAPPER

            CTRL -> TODOLISTENTRY** : create(greenSpace)
            activate TODOLISTENTRY

                TODOLISTENTRY -> TODOLISTENTRY : setDetails(taskDetails, urgency, duration)
                activate TODOLISTENTRY
                deactivate TODOLISTENTRY

                TODOLISTENTRY --> CTRL : toDoListEntry
            deactivate TODOLISTENTRY

            CTRL -> Repositories: getInstance()
            activate Repositories

                Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getToDoListRepository()
            activate REP

                REP --> CTRL: toDoListRepository
            deactivate REP

            CTRL -> toDoListRepository**: addToDoListEntry(toDoListEntry)
            activate toDoListRepository

                toDoListRepository --> CTRL: operation success
            deactivate toDoListRepository

            CTRL --> UI : operation success
        deactivate CTRL

        UI --> GSM : Displays operation success
    deactivate UI

deactivate GSM

@enduml
