@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "Repositories\n:Repositories" as ORG
participant "toDoList\n:ToDoList" as TODOLIST
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY

autonumber

group Get ToDo List Entry

-> ORG: getToDoListEntry(toDoListEntry)

autonumber 11
activate ORG

    ORG -> TODOLIST : getToDoListEntry(toDoListEntry)
    activate TODOLIST

        TODOLIST -> TODOLISTENTRY** : getToDoListEntry()
        activate TODOLISTENTRY

            TODOLISTENTRY --> TODOLIST : toDoListEntry
        deactivate TODOLISTENTRY

        TODOLIST --> ORG : toDoListEntry
    deactivate TODOLIST

    ORG --> UI : toDoListEntry
deactivate ORG

end
@enduml
