@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "Repositories\n:Repositories" as ORG
participant "toDoList\n:ToDoList" as TODOLIST
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "task\n:Task" as TASK

autonumber

group Get Task

-> ORG: getTask(toDoListEntry)

autonumber 11
activate ORG

    ORG -> TODOLIST : getTask(toDoListEntry)
    activate TODOLIST

        TODOLIST -> TODOLISTENTRY** : getTask()
        activate TODOLISTENTRY

            TODOLISTENTRY -> TASK** : getTask()
            activate TASK

                TASK --> TODOLISTENTRY : task
            deactivate TASK

            TODOLISTENTRY --> TODOLIST : task
        deactivate TODOLISTENTRY

        TODOLIST --> ORG : task
    deactivate TODOLIST

    ORG --> UI : task
deactivate ORG

end
@enduml
