@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "Repositories\n:Repositories" as ORG
participant "toDoList\n:ToDoList" as TODOLIST
participant "toDoListEntry\n:ToDoListEntry" as TODOLISTENTRY
participant "greenSpace\n:GreenSpace" as GREENSPACE

autonumber

group Get Green Space

-> ORG: getGreenSpace(toDoListEntry)

autonumber 11
activate ORG

    ORG -> TODOLIST : getGreenSpace(toDoListEntry)
    activate TODOLIST

        TODOLIST -> TODOLISTENTRY : getGreenSpace()
        activate TODOLISTENTRY

            TODOLISTENTRY -> GREENSPACE** : getGreenSpace()
            activate GREENSPACE

                GREENSPACE --> TODOLISTENTRY : greenSpace
            deactivate GREENSPACE

            TODOLISTENTRY --> TODOLIST : greenSpace
        deactivate TODOLISTENTRY

        TODOLIST --> ORG : greenSpace
    deactivate TODOLIST

    ORG --> UI : greenSpace
deactivate ORG

end
@enduml
