@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":AddEntryUI" as UI
participant ":AddEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "gsmRepository\n:GSMRepository" as GSMRepo
participant "greenSpaceRepository\n:GreenSpaceRepository" as GreenSpaceRepo
participant "entryRepository\n:EntryRepository" as EntryRepo
participant "GreenSpace" as GreenSpace
participant "Entry" as Entry

activate GSM

GSM -> UI : requests to add a new entry
activate UI

UI -> CTRL** : create
UI -> CTRL : getGreenSpacesManagedByGSM()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

    CTRL -> REP : getGSMRepository()
        activate REP

        REP --> CTRL : GSMRepo
        deactivate REP

    CTRL -> GSMRepo : getGreenSpacesManagedByGSM(gsm)
        activate GSMRepo

        GSMRepo -> GreenSpaceRepo : getGreenSpacesManagedByGSM(gsm)
            activate GreenSpaceRepo

            ref over GreenSpaceRepo
                Get Green Spaces Managed by GSM
            end

            GreenSpaceRepo --> GSMRepo : greenSpaces
        deactivate GreenSpaceRepo

        GSMRepo --> CTRL : greenSpaces
    deactivate GSMRepo

    CTRL --> UI : greenSpaces
deactivate CTRL

UI --> GSM : asks to select a green space
deactivate UI

GSM -> UI : selects a green space
activate UI

UI -> GSM : prompts to enter details for the new entry
deactivate UI

GSM -> UI : enters details for the new entry
activate UI

UI -> CTRL : addEntry(greenSpace, entryDetails)
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

    CTRL -> REP : getEntryRepository()
        activate REP

        REP --> CTRL : EntryRepo
        deactivate REP

    CTRL -> EntryRepo : createEntry(greenSpace, entryDetails)
        activate EntryRepo

        EntryRepo -> Entry : create(entryDetails)
            activate Entry

            ref over Entry
                Create new entry
            end

            Entry --> EntryRepo : entry
        deactivate Entry

        EntryRepo --> CTRL : successMessage
    deactivate EntryRepo

    CTRL --> UI : successMessage
deactivate CTRL

UI --> GSM : displays success message
deactivate UI

deactivate GSM
@enduml
