@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Organization{
    name
    address
}

class VFM {

}

class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}


VFM "1" -- "1..*" Vehicle: lists >

Organization "1" - "1..*" Vehicle: owns >
@enduml