@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Job {
    name
}

class Collaborator {
   name
   birthdate
   admissionDate
   address
   contactInfo
   idDocumentType
   idDocumentNumber
}

class HRM {
   name
   birthdate
   admissionDate
   address
   contactInfo
   idDocumentType
   idDocumentNumber
}

class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}

HRM "1" -- "1..*" Job : creates >
Collaborator "1" - "1..*" Job : has >
Collaborator <|-- HRM
GreenSpace "1" -- "1..*" Collaborator: contains >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
@enduml