@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
actor HRM
participant ":RegisterCollaboratorUI" as RegisterCollaboratorUI
participant ":RegisterCollaboratorController" as RegisterCollaboratorController
participant ":Repositories" as REP
participant "repositories:Repositories" as repositories
participant "collaboratorRepository\n:CollaboratorRepository" as CollaboratorRepository

activate HRM
HRM -> RegisterCollaboratorUI: Request to register a collaborator
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> HRM: Requests collaborator details
deactivate RegisterCollaboratorUI
HRM -> RegisterCollaboratorUI: Provides collaborator details
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> HRM: Shows details and requests confirmation
deactivate RegisterCollaboratorUI
HRM -> RegisterCollaboratorUI: Confirms details
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> RegisterCollaboratorController: RegisterCollaborator(name, birthdate,\n admissionDate, address, mobile phone,\n email, taxpayer number, idDocumentType,\n idDocumentNumber)
activate RegisterCollaboratorController
RegisterCollaboratorController -> REP: getInstance()
activate REP
REP -> RegisterCollaboratorController: repositories
deactivate REP
RegisterCollaboratorController -> repositories: getCollaboratorRepository()
activate repositories
repositories -> RegisterCollaboratorController: collaboratorRepository
deactivate repositories
RegisterCollaboratorController -> CollaboratorRepository: registerCollaborator(name, birthdate,\n admissionDate, address, mobile phone,\n email, taxpayer number, idDocumentType,\n idDocumentNumber)
activate CollaboratorRepository
        ref over CollaboratorRepository
            Register Collaborator

        end
        CollaboratorRepository --> RegisterCollaboratorController: collaborator
deactivate CollaboratorRepository
RegisterCollaboratorController --> RegisterCollaboratorUI: collaborator
deactivate RegisterCollaboratorController
RegisterCollaboratorUI --> HRM: display operation success
deactivate RegisterCollaboratorUI
deactivate HRM
@enduml