@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces Manager" as ADM
participant ":PostponeEntryUI" as UI
participant ":PostponeEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "taskRepository\n:TaskRepository" as taskRepository
participant "task\n:Task" as TASK

activate ADM

        ADM -> UI : asks to postpone a entry to a future date

        activate UI

        UI -> CTRL : getEntryList()
              activate CTRL

              CTRL -> RepositorySingleton : getInstance()
              activate RepositorySingleton

              RepositorySingleton -> CTRL : repositories
              deactivate RepositorySingleton
              CTRL -> PLAT : getTaskRepository()
              activate PLAT

              PLAT -> CTRL : taskRepository
              deactivate PLAT

              CTRL -> taskRepository : getEntryList()
              activate taskRepository

              taskRepository -> CTRL : entryList
              deactivate taskRepository

              CTRL -> UI : entryList
              deactivate CTRL
            loop
                UI --> ADM : shows registered entry's

                ADM -> UI : chooses entry to postpone
            end
            UI --> ADM : shows all chosen entry's and requests confirmation

            ADM -> UI : confirms data

            UI -> ADM : requests the date to which the entry's will be postpone

            ADM -> UI : types the new date

            UI -> CTRL : postponeEntry(entryList, date)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getTaskRepository()
                activate PLAT

                    PLAT --> CTRL: taskRepository
                deactivate PLAT

                CTRL -> taskRepository : postponeEntry(entryList, date)
                activate taskRepository

                taskRepository -> TASK**: postponeEntry(entryList, date)
                taskRepository -> taskRepository: postponeEntry(entryList, date)

                 activate taskRepository
                     taskRepository -> taskRepository: validatePostpone(date)
                     activate taskRepository
                                taskRepository --> CTRL : postponedEntry
                     deactivate taskRepository

                 deactivate taskRepository

                            deactivate taskRepository

            CTRL --> UI: postponedEntry
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml