@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Spaces\n Manager" as GSM
participant ":PostponeAgendaEntryUI" as UI
participant ":PostponeAgendaEntryController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "entryList\n:entryList" as ENTRYLIST
participant "agenda\n:Agenda" as AGENDA
participant ":EntryListMapper" as ENTRYLISTMAPPER
participant "listEntries\n:List<AgendaEntry>" as LISTENTRIES
participant "entryListDto\n:List<entriesListDto>" as TODOLISTDTO
participant "entryListDto\n:EntryListDto" as ENTRYLISTDTO
participant "agendaEntryList\n:AgendaEntryList" as AGENDAENTRYLIST
participant "greenSpace\n: GreenSpace" as GREENSPACE
participant "agendaEntry\n:AgendaEntry" as AGENDAENTRY

activate GSM

    GSM -> UI : asks to postpone a entry on the agenda
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getEntriesList()
        activate CTRL

           CTRL -> Repositories: getInstance()
           activate Repositories

                Repositories --> CTRL: repositories
           deactivate Repositories

           CTRL -> REP: getAgenda()
           activate REP

                REP --> CTRL: agenda
           deactivate REP

            CTRL -> ENTRYLIST : getAgendaEntryList()
            activate ENTRYLIST

                    ENTRYLIST --> LISTENTRIES** : create()
                    activate LISTENTRIES

                        loop for each agendaEntry
                            ENTRYLIST -> LISTENTRIES : add(agendaEntryList)
                            activate LISTENTRIES
                            deactivate LISTENTRIES
                        end

                        LISTENTRIES --> ENTRYLIST : listEntries
                    deactivate LISTENTRIES


                ENTRYLIST --> CTRL : listEntries
            deactivate ENTRYLIST

            CTRL -> ENTRYLISTMAPPER** : entryListToDto(listEntries)
            activate ENTRYLISTMAPPER

                ENTRYLISTMAPPER --> TODOLISTDTO** : create()

                loop for each agendaEntry
                    ENTRYLISTMAPPER -> LISTENTRIES : get(i)
                    activate LISTENTRIES

                    LISTENTRIES --> ENTRYLISTMAPPER : agendaEntry
                    deactivate LISTENTRIES

                    ENTRYLISTMAPPER -> ENTRYLISTMAPPER : entryListDto = toDTO(agendaEntry)
                    activate ENTRYLISTMAPPER
                    deactivate ENTRYLISTMAPPER

                    ENTRYLISTMAPPER --> ENTRYLISTDTO** : create()
                    activate ENTRYLISTDTO

                    ENTRYLISTDTO --> ENTRYLISTMAPPER : entryListDto
                    deactivate ENTRYLISTDTO

                    ENTRYLISTMAPPER -> TODOLISTDTO : add(entryListDto)
                    activate TODOLISTDTO
                    deactivate TODOLISTDTO

                end

                ENTRYLISTMAPPER --> CTRL : entryListDto
            deactivate ENTRYLISTMAPPER

            CTRL --> UI : entryListDto
        deactivate CTRL
        loop
        UI --> GSM: shows all the entries registered in the \nAgenda and asks you to select the \nones you want to postpone
    deactivate UI

    GSM -> UI: select the desired entries and \nthe date to postpone them
    activate UI
        end

        UI -> CTRL : getGreenSpace()
        activate CTRL

            CTRL -> ENTRYLIST : getGreenSpace()
            activate ENTRYLIST

                ENTRYLIST -> AGENDAENTRYLIST : getGreenSpace()
                activate AGENDAENTRYLIST

                    AGENDAENTRYLIST -> GREENSPACE** : getGreenSpace()
                    activate GREENSPACE

                        GREENSPACE --> AGENDAENTRYLIST : greenSpace
                    deactivate GREENSPACE

                    AGENDAENTRYLIST --> ENTRYLIST : greenSpace
                deactivate AGENDAENTRYLIST

                ENTRYLIST --> CTRL : greenSpace
            deactivate ENTRYLIST

            CTRL --> UI : greenSpace
        deactivate CTRL

        UI -> CTRL : postponeAgendaEntry(chosenEntryList, greenSpace, newDate)
        activate CTRL

            CTRL -> Repositories: getInstance()
            activate Repositories

                Repositories --> CTRL: repositories
            deactivate Repositories

            CTRL -> REP: getAgenda()
            activate REP

                REP --> CTRL: agenda
            deactivate REP

            CTRL -> AGENDA** : postponeAgendaEntry(chosenEntryList, greenSpace, newDate)
            activate AGENDA

                AGENDA -> AGENDAENTRY** : postponeAgendaEntry(chosenEntryList, greenSpace, newDate)
                loop for each entry on the chosenEntryList
                AGENDA -> AGENDA : postponeEntry(entry, newDate)
                activate AGENDA
                end
                deactivate AGENDA
                deactivate AGENDAENTRY

                AGENDA --> CTRL : postponedAgendaEntries
                deactivate AGENDA

            CTRL --> UI : postponedAgendaEntries
            deactivate CTRL

        UI --> GSM: shows all data and requests confirmation
    deactivate UI

    GSM -> UI: confirms data
    activate UI

        UI -> CTRL : postponeAgendaEntries(postponedAgendaEntries)
        activate CTRL

            CTRL -> AGENDA : postponeAgendaEntry(postponedAgendaEntries))
            activate AGENDA

            AGENDA -> AGENDA : validateEntries()
            activate AGENDA

            deactivate AGENDA

            AGENDA --> CTRL : operation success
            deactivate AGENDA

            CTRL --> UI : operation success
        deactivate CTRL

        UI --> GSM: displays operation success
    deactivate UI

deactivate GSM

@enduml