@startuml
'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false

class Collaborator {
    + getCollaborator()
}

class RecordTaskCompletionUI {
    + markTaskAsCompleted(task: Task)
}

class RecordTaskCompletionController {
    - collaboratorRepository: CollaboratorRepository
    - taskRepository: TaskRepository
    + RecordTaskCompletionController(collaboratorRepository: CollaboratorRepository, taskRepository: TaskRepository)
    + markTaskAsCompleted(task: Task)
}

class Repositories {
    + Repositories()
    + getInstance(): Repositories
    + getCollaboratorRepository(): CollaboratorRepository
    + getTaskRepository(): TaskRepository
}

class CollaboratorRepository {
    + getCollaborator(): Collaborator
}

class TaskRepository {
    + markTaskAsCompleted(task: Task): String
}

class Task {
    - taskId: String
    - taskName: String
    - description: String
    - status: String
    + Task(taskId: String, taskName: String, description: String, status: String)
    + getTaskId(): String
    + getTaskName(): String
    + getDescription(): String
    + getStatus(): String
}

RecordTaskCompletionUI --> RecordTaskCompletionController
RecordTaskCompletionController --> Collaborator : collaboratorRepository
RecordTaskCompletionController --> TaskRepository : taskRepository
RecordTaskCompletionController --> Task : markTaskAsCompleted
RecordTaskCompletionController --> Repositories : getInstance
RecordTaskCompletionController --> Repositories : getTaskRepository
RecordTaskCompletionController --> Repositories : getCollaboratorRepository
TaskRepository --> Task : markTaskAsCompleted
Task <-- TaskRepository : returns
@enduml
