@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":RecordTaskCompletionController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "taskRepository\n:TaskRepository" as taskRepository

autonumber 3

-> CTRL : getTaskList(collaborator, dateI, dateF, typeStatus)
autonumber 3.1
activate CTRL
    group Get Tasks for Collaborator

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
        activate REP

            REP --> CTRL : taskRepository
        deactivate REP

        CTRL -> taskRepository : getTaskList(collaborator, dateI, dateF, typeStatus)
        activate taskRepository

            taskRepository --> CTRL : taskList
        deactivate taskRepository

    end
autonumber 4
        <-- CTRL : taskList
deactivate CTRL

@enduml

