@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":RecordTaskCompletionController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "taskRepository\n:TaskRepository" as taskRepository

autonumber 5

-> CTRL : markTaskAsCompleted(task)
autonumber 5.1
activate CTRL
    group Mark Task as Completed

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> REP : getTaskRepository()
        activate REP

            REP --> CTRL : taskRepository
        deactivate REP

        CTRL -> taskRepository : markTaskAsCompleted(task)
        activate taskRepository

            taskRepository --> CTRL : successMessage
        deactivate taskRepository

    end
autonumber 6
        <-- CTRL : successMessage
deactivate CTRL

@enduml
