@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Col
participant ":RecordTaskCompletionUI" as UI
participant ":RecordTaskCompletionController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "taskRepository\n:TaskRepository" as taskRepository
participant "task:Task" as TASK

activate Col

Col -> UI : requests to record task completion
activate UI

UI -> CTRL** : create
UI -> CTRL : getCollaboratorByEmail(email)
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton

CTRL -> REP : getCollaboratorRepository
activate REP

REP --> CTRL : collaboratorRepository
deactivate REP

CTRL -> collaboratorRepository : getCollaboratorByEmail(email)
activate collaboratorRepository

ref over collaboratorRepository
    Get Collaborator by Email
end

collaboratorRepository --> CTRL : collaborator
deactivate collaboratorRepository
CTRL --> UI : collaborator
deactivate CTRL

UI --> Col : prompts to select the task to mark as completed
deactivate UI

Col -> UI : selects the task to mark as completed
activate UI

UI -> CTRL : getTaskList(collaborator, dateI, dateF, typeStatus)
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton

CTRL -> REP : getTaskRepository()
activate REP

REP --> CTRL : taskRepository
deactivate REP

CTRL -> taskRepository : getTaskList(collaborator, dateI, dateF, typeStatus)
activate taskRepository

ref over taskRepository
    Get Task List
end

taskRepository --> CTRL : taskList
deactivate taskRepository

CTRL --> UI : taskList
deactivate CTRL

UI --> Col : displays the task list for selection
deactivate UI

Col -> UI : selects the task to mark as completed
activate UI

UI -> CTRL : markTaskAsCompleted(task)
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton

CTRL -> REP : getTaskRepository()
activate REP

REP --> CTRL : taskRepository
deactivate REP

CTRL -> taskRepository : markTaskAsCompleted(task)
activate taskRepository

ref over taskRepository
    Mark Task as Completed
end

taskRepository --> CTRL : successMessage
deactivate taskRepository

CTRL --> UI : successMessage
deactivate CTRL

UI --> Col : displays success message
deactivate UI

deactivate Col
@enduml
