@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Col
participant ":RecordCompletionUI" as UI
participant ":RecordCompletionController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "agenda\n:Agenda" as AGENDA
participant "agendaEntry\n:AgendaEntry" as AGENDAENTRY
participant "agendaEntries\n:List<AgendaEntry>" as AGENDAENTRIES
participant ":AgendaEntryMapper" as Mapper
participant "listAgendaEntriesDto\n:List<AgendaEntryDto>" as ListAgendaEntriesDto
participant "agendaEntryDto\n:AgendaEntryDto" as DTO

activate Col

Col -> UI : Requests to record task completion
activate UI

UI -> CTRL** : Create

UI -> CTRL : getCollaboratorByEmail(email)
activate CTRL

    CTRL -> _APP**: getInstance()
    activate _APP

        _APP -> CTRL: appSession
    deactivate _APP

    CTRL -> APP**: getCurrentSession()
    activate APP

        APP --> CTRL: currentSession
    deactivate APP

    CTRL -> SESSION**: getUserEmail()
    activate SESSION

        SESSION --> CTRL: email
    deactivate SESSION

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
    deactivate RepositorySingleton

    CTRL -> REP : getCollaboratorRepository()
    activate REP

        REP --> CTRL : collaboratorRepository
    deactivate REP

        CTRL -> collaboratorRepository : getCollaboratorByEmail(email)
            activate collaboratorRepository

            collaboratorRepository -> collaboratorRepository : getCollaboratorByEmail(email)
            activate collaboratorRepository

            deactivate collaboratorRepository

        collaboratorRepository --> CTRL : collaborator
    deactivate collaboratorRepository

CTRL --> UI : collaborator
deactivate CTRL

UI -> Col : Asks to select the beginning and end date of the search
deactivate UI

Col -> UI : Selects the beginning and end date
activate UI

UI -> CTRL : getTaskList(collaborator, dateI, dateF, typeStatus)
activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
    deactivate RepositorySingleton

    CTRL -> REP : getAgenda()
    activate REP

        REP --> CTRL : agenda
    deactivate REP

    CTRL -> AGENDA : getCollaboratorAgendaEntries(collaborator, dateI, dateF, typeStatus)
    activate AGENDA

        AGENDA --> AGENDAENTRIES** : create()
            loop for each agendaEntry in the specified date range and status
                AGENDA -> AGENDAENTRIES : add(agendaEntry)
                activate AGENDAENTRIES
            end
        AGENDAENTRIES --> AGENDA : agendaEntryList
        deactivate AGENDAENTRIES
    AGENDA --> CTRL : agendaEntryList
    deactivate AGENDA

    CTRL -> Mapper : toDTOList(agendaEntryList)
    activate Mapper

        Mapper --> ListAgendaEntriesDto** : create()
            loop for each agendaEntry in agendaEntryList
                Mapper -> AGENDAENTRIES : get(i)
                    activate AGENDAENTRIES

                    AGENDAENTRIES --> Mapper : agendaEntry
                    deactivate AGENDAENTRIES
                Mapper -> DTO : toDTOEntry(agendaEntry)
                    activate DTO

                    DTO --> Mapper : agendaEntryDto
                    deactivate DTO
                Mapper -> ListAgendaEntriesDto : add(agendaEntryDto)
                    activate ListAgendaEntriesDto
            end
        ListAgendaEntriesDto --> Mapper : agendaEntryListDto
        deactivate ListAgendaEntriesDto

    Mapper --> CTRL : agendaEntryListDto
    deactivate Mapper

CTRL --> UI : agendaEntryListDto
deactivate CTRL

UI --> Col : Displays the list of tasks
deactivate UI

Col -> UI : Selects the task to mark as completed
activate UI

UI -> CTRL : markTaskAsCompleted(taskId)
activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

        RepositorySingleton --> CTRL : repositories
    deactivate RepositorySingleton

    CTRL -> REP : getAgenda()
    activate REP

        REP --> CTRL : agenda
    deactivate REP

    CTRL -> AGENDA : getAgendaEntry(taskId)
    activate AGENDA

        AGENDA --> CTRL : agendaEntry
    deactivate AGENDA

    CTRL -> AGENDAENTRY : markAsCompleted()
    activate AGENDAENTRY

    AGENDAENTRY --> CTRL : operation success
    deactivate AGENDAENTRY

    CTRL -> Mapper : toDTO(agendaEntry)
    activate Mapper

        Mapper -> DTO : toDTOEntry(agendaEntry)
        activate DTO

            DTO --> Mapper : agendaEntryDto
        deactivate DTO

    Mapper --> CTRL : agendaEntryDto
    deactivate Mapper

CTRL --> UI : agendaEntryDto
deactivate CTRL

UI --> Col : Shows task completion confirmation
deactivate UI

deactivate Col

@enduml
