@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Human Resources\n Manager" as HRM
participant ":AssignSkillsUI" as UI
participant ":AssignSkillsController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "skillRepository\n:SkillRepository" as SKILLREP
participant "collaboratorRepository\n:CollaboratorRepository" as COLREP
participant "collaborator\n:Collaborator" as COLLAB
participant "skill\n:Skill" as SKILL

activate HRM

HRM -> UI : requests to assign skills to a collaborator
activate UI

UI -> CTRL** : generate

UI -> CTRL : listSkills()
activate CTRL

CTRL -> Repositories: getInstance()
activate Repositories

Repositories --> CTRL: repositories
deactivate Repositories

CTRL -> REP: getSkillRepository()
activate REP

REP --> CTRL: skillRepository
deactivate REP

CTRL -> SKILLREP : listSkills()
activate SKILLREP

SKILLREP --> CTRL : skills
deactivate SKILLREP

CTRL --> UI : skills
deactivate CTRL

loop While selecting skills
    UI --> HRM: shows the list of skills and asks you to \nselect one or more skills
    deactivate UI

    HRM -> UI: selects the skill(s)
    activate UI
end

UI -> CTRL: getCollaborators()
activate CTRL

CTRL -> Repositories: getInstance()
activate Repositories

Repositories --> CTRL: repositories
deactivate Repositories

CTRL -> REP: getCollaboratorRepository()
activate REP

REP --> CTRL: collaboratorRepository
deactivate REP

CTRL -> COLREP: getCollaborator(collaboratorID)
activate COLREP

COLREP -> COLLAB**: Collaborator(collaboratorID)
activate COLLAB

loop For each skill
    COLLAB -> COLLAB: addSkill(skill)
    activate COLLAB
end

COLLAB --> COLREP: updatedCollaborator
deactivate COLLAB

COLREP --> CTRL: updatedCollaborator
deactivate COLREP

CTRL --> UI: updatedCollaborator
deactivate CTRL

UI --> HRM: displays operation success
deactivate UI

deactivate HRM
@enduml
