@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US04: Assign Skills to Collaborator

actor HRM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as repositories
participant "skillRepository\n:SkillRepository" as SKILLREP
participant "collaboratorRepository\n:CollaboratorRepository" as COLREP
participant "collaborator:\nCollaborator" as COLLAB

activate HRM

HRM -> UI : Request to assign one or more skills to a collaborator
activate UI

UI -> CTRL** : generate
UI -> CTRL: listSkills()
activate CTRL

CTRL -> REP: getInstance()
activate REP

REP --> CTRL: repositories
deactivate REP

CTRL -> repositories: getSkillRepository()
activate repositories

repositories --> CTRL: skillRepository
deactivate repositories

CTRL -> SKILLREP : listSkills()
activate SKILLREP

SKILLREP --> CTRL : skills
deactivate SKILLREP

CTRL --> UI: skills
deactivate CTRL

UI --> HRM: Displays a list of available skills
deactivate UI

loop
HRM -> UI : selects a skill
activate UI

UI --> HRM: asks if you want to add more skills or continue the program
deactivate UI

end

HRM -> UI : Provides collaborator details
activate UI

UI -> CTRL: getCollaborator()
activate CTRL

CTRL -> REP: getInstance()
activate REP

REP --> CTRL: repositories
deactivate REP

CTRL -> repositories: getCollaboratorRepository()
activate repositories

repositories --> CTRL: collaboratorRepository
deactivate repositories

CTRL -> COLREP: getCollaborator()
activate COLREP

COLREP --> CTRL: collaborator
deactivate COLREP

CTRL --> UI: collaborator
deactivate CTRL

UI --> HRM : Shows details and requests confirmation
deactivate UI

HRM -> UI : Confirms details
activate UI

UI -> CTRL: assignSkill(collaborator, skills)
activate CTRL

CTRL -> COLREP: assignSkill(collaborator, skills)
activate COLREP

COLREP -> COLLAB**: assignSkill(collaborator, skills)
activate COLLAB

COLLAB -> COLLAB: validateSkills(skills)
activate COLLAB

COLLAB -> COLLAB: addCollaboratorSkills(skills)
activate COLLAB

COLLAB --> COLREP: collaborator
deactivate COLLAB

COLREP --> CTRL: collaborator
deactivate COLREP

CTRL --> UI: collaborator
deactivate CTRL

UI --> HRM: success
deactivate UI

deactivate HRM

@enduml
