@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Human Resources\nManager" as HRM
participant ":AssignSkillsUI" as UI
participant ":AssignSkillsController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as COLREP
participant "collaborator\n:Collaborator" as COLLAB
participant "skill\n:Skill" as SKILL

activate HRM

HRM -> UI : Requests to assign skills to a collaborator
activate UI

UI -> CTRL** : Generate

UI -> CTRL: getCollaborators()
activate CTRL

CTRL -> Repositories: getInstance()
activate Repositories

Repositories --> CTRL: repositories
deactivate Repositories

CTRL -> COLREP: getCollaboratorRepository()
activate COLREP

COLREP --> CTRL: collaboratorRepository
deactivate COLREP

CTRL -> COLREP: getCollaborator(collaboratorID)
activate COLREP

COLREP -> COLLAB**: Collaborator()
activate COLLAB

COLLAB --> COLREP: updatedCollaborator
deactivate COLLAB

COLREP --> CTRL: updatedCollaborator
deactivate COLREP

CTRL --> UI: updatedCollaborator
deactivate CTRL

UI -> CTRL : ListSkills()
activate CTRL

CTRL -> Repositories: getInstance()
activate Repositories

Repositories --> CTRL: repositories
deactivate Repositories

CTRL -> REP: getSkillRepository()
activate REP

REP --> CTRL: skillRepository
deactivate REP

CTRL -> SKILLREP** : listSkills()
activate SKILLREP

SKILLREP --> CTRL : skills
deactivate SKILLREP

CTRL --> UI : skills
deactivate CTRL




UI -> CTRL: assignSkillsToCollaborator(collaborator, skills)
activate CTRL

CTRL -> Repositories: getInstance()
activate Repositories

Repositories --> CTRL: repositories
deactivate Repositories

CTRL -> COLREP: getCollaboratorRepository()
activate COLREP

COLREP --> CTRL: collaboratorRepository
deactivate COLREP

CTRL -> COLREP: getCollaborator(collaboratorID)
activate COLREP

COLREP -> COLLAB**: Collaborator()
activate COLLAB

COLLAB -> COLLAB: validateCollaborator()
activate COLLAB

COLLAB --> COLREP: validatedCollaborator
deactivate COLLAB

COLREP --> CTRL: validatedCollaborator
deactivate COLREP

CTRL --> UI: validatedCollaborator
deactivate CTRL

UI --> HRM: Displays operation success
deactivate UI

deactivate HRM
@enduml
