@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "collaboratorRepository\n:CollaboratorRepository" as COLREP
participant "skillRepository\n:SkillRepository" as SKILLREP
participant "collaborator" as collaborator

autonumber 11
-> COLREP : getCollaborator(collaboratorId)

autonumber 11.1
activate COLREP

    COLREP --> collaborator: collaborator

autonumber 12
--> SKILLREP : getSkill(skillName)

autonumber 12.1
activate SKILLREP

    SKILLREP --> SKILLREP: skill

    SKILLREP --> collaborator: skill

autonumber 12.2
activate collaborator

    collaborator --> SKILLREP: assigned skill

autonumber 12.3
deactivate collaborator

deactivate SKILLREP

deactivate COLREP

@enduml
