@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Collaborator {
    - name: String
    - birthdate: String
    - admissionDate: String
    - address: String
    - contactInfo: String
    - taxpayerNumber: String
    - idDocumentType: String
    - idDocumentNumber: String
    + Collaborator(name, birthdate, admissionDate, address, contactInfo, taxpayerNumber, idDocumentType, idDocumentNumber)
    + assignSkill(skill)
}

class Skill {
    - name: String
    + Skill(name)
}

class AssignSkillController {
    + AssignSkillController(collaboratorRepository, skillRepository)
    + assignSkill(collaboratorId, skillName)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getCollaboratorRepository() : Repositories
    + getSkillRepository() : Repositories
}

class CollaboratorRepository {
    + addCollaborator(collaborator)
    + getCollaborator(collaboratorId)
}

class SkillRepository {
    + addSkill(skill)
    + getSkill(skillName)
}

Collaborator "1" --> "*" Skill : has
AssignSkillController .> CollaboratorRepository : collaboratorRepository
AssignSkillController .> SkillRepository : skillRepository

@enduml
