@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources\n Manager" as HRM
participant ":AssignSkillController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as COLREP
participant "skillRepository\n:SkillRepository" as SKILLREP

activate HRM

    HRM -> CTRL : assigns a skill to a collaborator
    activate CTRL

        CTRL -> Repositories: getInstance()
        activate Repositories

            Repositories --> CTRL: repositories
        deactivate Repositories

        CTRL -> REP: getCollaboratorRepository()
        activate REP

            REP --> CTRL: collaboratorRepository
        deactivate REP

        CTRL -> SKILLREP : getSkillRepository()
        activate SKILLREP

            SKILLREP --> CTRL: skillRepository
        deactivate SKILLREP

        CTRL -> CTRL: assignSkill(collaboratorId, skillName)

    deactivate CTRL

    HRM -> CTRL : assigns a skill to a collaborator
    activate CTRL

        CTRL -> Repositories: getInstance()
        activate Repositories

            Repositories --> CTRL: repositories
        deactivate Repositories

        CTRL -> REP: getCollaboratorRepository()
        activate REP

            REP --> CTRL: collaboratorRepository
        deactivate REP

        CTRL -> SKILLREP : getSkillRepository()
        activate SKILLREP

            SKILLREP --> CTRL: skillRepository
        deactivate SKILLREP

        CTRL -> CTRL: assignSkill(collaboratorId, skillName)

        alt Skill and collaborator exist
            CTRL -> COLREP: getCollaborator(collaboratorId)
            activate COLREP

                COLREP --> CTRL: collaborator
            deactivate COLREP

            CTRL -> SKILLREP: getSkill(skillName)
            activate SKILLREP

                SKILLREP --> CTRL: skill
            deactivate SKILLREP

            CTRL -> collaborator: assignSkill(skill)
            activate collaborator

                collaborator --> CTRL: assigned skill
            deactivate collaborator

            CTRL --> HRM: success
        else Skill or collaborator does not exist
            CTRL --> HRM: failure
        end

    deactivate CTRL

deactivate HRM

@enduml
