@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":GreenSpaceMapper" as Mapper
participant "greenSpaceDto\n:GreenSpaceDto" as DTO
participant "greenSpaceList\n:List<GreenSpace>" as greenSpaceList
participant "greenSpaceListDto\n:List<GreenSpaceDto>" as LISTDTO

autonumber 10

 -> Mapper : toDto(greenSpaceList)
autonumber 10.1
activate Mapper
    group Create a copy of GreenSpace list

            Mapper --> LISTDTO** : create()
                loop for each entry in entryList
                    Mapper -> greenSpaceList : get(i)
                        activate greenSpaceList

                        greenSpaceList --> Mapper : entry
                        deactivate greenSpaceList
                    Mapper -> DTO : toDTOEntry(entry)
                        activate DTO

                        DTO --> Mapper : entryDto
                        deactivate DTO
                    Mapper -> LISTDTO : add(taskDto)
                        activate LISTDTO
                end


            LISTDTO --> Mapper : listEntriesDto
             deactivate LISTDTO
    end
    autonumber 11

    <-- Mapper  : greenSpaceListDto

deactivate Mapper

deactivate Mapper

@enduml