@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green\nSpace Manager\n(GSM)" as GSM
participant ":ListGreenSpaceUI" as UI
participant ":ListGreenSpaceController" as CTRL

participant "GreenSpaceMapper" as Mapper

activate GSM

        GSM -> UI : asks to list all the GreenSpaces managed by him

        activate UI

                UI -> CTRL** : create

                UI -> CTRL : getCollaboratorByEmail(email)

                    activate CTRL
                        ref over CTRL
                            Get GSM by Email

                        end
                        CTRL --> UI :greenSpaceManager
                    deactivate CTRL
            UI --> GSM : asks the user to choose a sorting option
        deactivate UI

        GSM -> UI : chooses a sorting option
        activate UI

                UI --> GSM : asks for confirmation
        deactivate UI

            GSM -> UI : confirms that he wants to create the list
        activate UI


            UI -> CTRL : getGreenSpaceList(greenSpaceManger,sortingOption)
            activate CTRL
                    ref over CTRL
                            Get GreenSpace List

                    end
                    CTRL -> Mapper : toDto(greenSpaceList)
                    activate Mapper
                            ref over Mapper
                                    Create a copy of GreenSpace list

                            end
                            Mapper -->CTRL : greenSpaceListDto
                    deactivate Mapper

            CTRL --> UI: greenSpaceListDto

            deactivate CTRL
            UI --> GSM: shows the list
    deactivate UI

deactivate GSM


@enduml