@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":MaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "greenSpaceRepository\n:GreenSpaceRepository" as greenSpaceRepository
participant "greenSpaceList\n:List<GreenSpace>" as greenSpaceList
participant ":GreenSpaceMapper" as Mapper

autonumber 9

 -> CTRL : getGreenSpaceList(greenSpaceManager,sortingOption)
autonumber 9.1
activate CTRL
    group Get GreenSpace List




                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> REP : getGreenSpaceRepository()
                activate REP

                    REP --> CTRL: greenSpaceRepository
                deactivate REP

                CTRL -> greenSpaceRepository : getGreenSpaceList(greenSpaceManager,sortingOption)

                activate greenSpaceRepository

                        greenSpaceRepository -> greenSpaceList**: create()
                        loop for each greenSpace in greenSpaceList
opt greenSpace.getGSM() == greenSpaceManager
                            greenSpaceRepository -> greenSpaceList : add(greenSpaceManager)
                                activate greenSpaceList





                                        end

                                        end
                                        greenSpaceList -> greenSpaceList : sort(sortingOption)
                                        activate greenSpaceList

                                                greenSpaceList --> greenSpaceRepository: greenSpaceList

                                        deactivate greenSpaceList

                                deactivate greenSpaceList

                        greenSpaceRepository --> CTRL : greenSpaceList


                deactivate greenSpaceRepository



    end
    autonumber 10
    CTRL -> Mapper : toDto(greenSpaceList)
        activate Mapper


@enduml