@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green\nSpace Manager\n(GSM)" as GSM
participant ":ListGreenSpaceUI" as UI
participant ":ListGreenSpaceController" as CTRL
participant "GreenSpaceMapper" as Mapper

activate GSM

        GSM -> UI : asks to list all the GreenSpaces

        activate UI

            UI --> GSM : asks for confirmation

            GSM -> UI : confirms that he wants to create the list
            UI -> CTRL** : create
            UI -> CTRL : getGreenSpaceList()
            activate CTRL
                    ref over CTRL
                            Get GreenSpace List

                    end
                    CTRL -> Mapper : toDto(greenSpaceList)
                    activate Mapper
                            ref over Mapper
                                    Create a copy of GreenSpace list

                            end
                            Mapper -->CTRL : greenSpaceListDto
                    deactivate Mapper

            CTRL --> UI: greenSpaceListDto

            deactivate CTRL
            UI --> GSM: shows the list
    deactivate UI

deactivate GSM


@enduml