@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green\nSpace Manager\n(GSM)" as GSM
participant ":ListGreenSpaceUI" as UI
participant ":ListGreenSpaceController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as REP
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "greenSpaceRepository\n:GreenSpaceRepository" as greenSpaceRepository
participant "em\n:ExternalModule" as EM
participant "refValue\n:RefValue" as RefValue
participant ":GreenSpaceMapper" as Mapper
participant "greenSpaceList\n:List<GreenSpace>" as greenSpaceList
participant "greenSpaceDto\n:GreenSpaceDto" as DTO
participant "greenSpaceListDto\n:List<GreenSpaceDto>" as LISTDTO

activate GSM

        GSM -> UI : asks to list all greenSpaces managed by him

        activate UI

                UI -> CTRL** : create
                    UI -> CTRL : getCollaboratorByEmail(email)
                        activate CTRL
                        CTRL -> CTRL : getCollaboratorFromSession()
                        activate CTRL

                        CTRL -> _APP**: getInstance()
                                   activate _APP

                                        _APP -> CTRL: appSession
                                   deactivate _APP

                                   CTRL -> APP**: getCurrentSession()
                                   activate APP

                                        APP --> CTRL: currentSession
                                   deactivate APP

                                   CTRL -> SESSION**: getUserEmail()
                                   activate SESSION

                                        SESSION --> CTRL: email
                                   deactivate SESSION
                        CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                            RepositorySingleton --> CTRL : repositories
                            deactivate RepositorySingleton

                        CTRL -> REP : getCollaboratorRepository
                            activate REP

                            REP --> CTRL : collaboratorRepository
                            deactivate REP

                        CTRL -> collaboratorRepository : getCollaboratorByEmail(email)
                            activate collaboratorRepository

                            collaboratorRepository -> collaboratorRepository : getCollaboratorByEmail(email)
                            activate collaboratorRepository

                            collaboratorRepository --> CTRL : greenSpaceManager
                                deactivate collaboratorRepository

                                deactivate collaboratorRepository
                            CTRL --> CTRL : greenSpaceManager
                                deactivate CTRL



                        CTRL --> UI : greenSpaceManager
                        deactivate CTRL

                    UI -> CTRL : getSortingOptions()
                        activate CTRL

                            CTRL -> RepositorySingleton: getInstance()
                            activate RepositorySingleton

                                RepositorySingleton --> CTRL : repositories
                            deactivate RepositorySingleton

                            CTRL -> REP : getGreenSpaceRepository()
                            activate REP

                                REP --> CTRL: greenSpaceRepository
                            deactivate REP

                            CTRL -> greenSpaceRepository : getSortingOptions()
                            activate greenSpaceRepository
                                greenSpaceRepository -> greenSpaceRepository : getConfigurationsFromFile()
                                activate greenSpaceRepository

                                greenSpaceRepository --> CTRL: sortingOptions
                                deactivate greenSpaceRepository

                            deactivate greenSpaceRepository
                            CTRL --> UI : sortingOptions
                        deactivate CTRL


            UI --> GSM : asks the user to choose a sorting option
        deactivate UI

        GSM -> UI : chooses a sorting option
        activate UI

            UI --> GSM: asks for confirmation
        deactivate UI
            GSM -> UI : confirms that he wants to create the list
        activate UI


            UI -> CTRL : getGreenSpaceList(greenSpaceManager,sortingOption)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> REP : getGreenSpaceRepository()
                activate REP

                    REP --> CTRL: greenSpaceRepository
                deactivate REP

                CTRL -> greenSpaceRepository : getGreenSpaceList(greenSpaceManager,sortingOption)

                activate greenSpaceRepository

                        greenSpaceRepository -> greenSpaceList**: create()
                        loop for each greenSpace
opt greenSpace.getGSM() == greenSpaceManager
                            greenSpaceRepository -> greenSpaceList : add(greenSpace)
                                activate greenSpaceList





                                        end

                                        end


                                                greenSpaceList --> greenSpaceRepository: greenSpaceList


                                deactivate greenSpaceList


                                    greenSpaceRepository -> greenSpaceRepository : getExternalModule()

                                    activate greenSpaceRepository

                                        greenSpaceRepository --> EM : getReferenceValue(sortingOption)
                                        activate EM

                                                EM -> RefValue** : create(sortingOption)
                                        EM --> greenSpaceRepository : refValue
                                        deactivate EM

                                        greenSpaceRepository --> greenSpaceList : sortList(refValue)
                                        activate greenSpaceList
                                                greenSpaceList -> greenSpaceList : sortList(refValue)
                                                activate greenSpaceList

                                                    greenSpaceList --> greenSpaceRepository : greenSpaceList
                                                deactivate greenSpaceList

                                        deactivate greenSpaceList

                        greenSpaceRepository --> CTRL : greenSpaceList

                        deactivate greenSpaceRepository

                deactivate greenSpaceRepository



            CTRL -> Mapper : toDTO(greenSpaceList)
            activate Mapper

            Mapper --> LISTDTO** : create()
                loop for each greenSpace in greenSpaceList
                    Mapper -> greenSpaceList : get(i)
                        activate greenSpaceList

                        greenSpaceList --> Mapper : greenSpace
                        deactivate greenSpaceList
                    Mapper -> DTO : toDTOEntry(greenSpace)
                        activate DTO

                        DTO --> Mapper : greenSpaceDto
                        deactivate DTO
                    Mapper -> LISTDTO : add(greenSpaceDto)
                        activate LISTDTO
                end


            LISTDTO --> Mapper : greenSpaceListDto
             deactivate LISTDTO
            Mapper --> CTRL : greenSpaceListDto

            deactivate Mapper
            CTRL --> UI: greenSpaceListDto
            deactivate CTRL
            UI --> GSM: shows the list
    deactivate UI

deactivate GSM



@enduml