@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":GreenSpaceMapper" as Mapper
participant "greenSpaceDto\n:GreenSpaceDto" as DTO
participant "greenSpaceList\n:List<GreenSpace>" as greenSpaceList
participant "greenSpaceListDto\n:List<GreenSpaceDto>" as LISTDTO

autonumber 12

 -> Mapper : toDto(greenSpaceList)
autonumber 12.1
activate Mapper
    group Create a copy of GreenSpace list

            Mapper --> LISTDTO** : create()
                loop for each greenSpace in greenSpaceList
                    Mapper -> greenSpaceList : get(i)
                        activate greenSpaceList

                        greenSpaceList --> Mapper : greenSpace
                        deactivate greenSpaceList
                    Mapper -> DTO : toDTOEntry(greenSpace)
                        activate DTO

                        DTO --> Mapper : greenSpaceDto
                        deactivate DTO
                    Mapper -> LISTDTO : add(greenSpaceDto)
                        activate LISTDTO
                end


            LISTDTO --> Mapper : greenSpaceListDto
             deactivate LISTDTO
    end
    autonumber 13

    <-- Mapper  : greenSpaceListDto

deactivate Mapper

deactivate Mapper

@enduml