@startuml
'skinparam monochrome true
skinparam packageStyle Folder
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

package UI{
class ListGreenSpaceUI{

}
}
package Controller{
class ListGreenSpaceController{
    + getGreenSpaceList()
    + createListGreenSpaceController()
    + toDto(greenSpaceList)
}
}
package Domain{
package Mapper{
class GreenSpaceMapper{
    - greenSpaceListDto
    + toDto(greenSpaceList)
    + addGreenSpace(greenSpaceDto)
}
package Dto{
class GreenSpaceDto{
    - name
    - dimension
    - address
    + greenSpaceDto(greenSpace)
}
}
}
package Domain.Reository{
class GreenSpaceRepository{
    - greenSpaceList
    + getGreenSpaceList()
}


class Repositories{
 - Repositories()
 + getGreenSpaceRepository(): Repositories
 + getInstance(): Repositories
}
}
}
ListGreenSpaceUI .> ListGreenSpaceController
ListGreenSpaceController ..> Repositories : repositories
Repositories -> Repositories : instance
ListGreenSpaceController ..> GreenSpaceRepository: greenSpaceRepository
Repositories "1" --> "1" GreenSpaceRepository
ListGreenSpaceController "1" -> "1" GreenSpaceMapper: greenSpaceList
GreenSpaceMapper "1" -> "1" GreenSpaceDto: greenSpace
@enduml