@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle for inspection
    activate System

        System --> Employee : requests data (i.e. designation of the vehicle, cost)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml