@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle for inspection
    activate System

        System --> Employee : shows a list of registered vehicles
    deactivate System

    Employee -> System : selects vehicle
    activate System

        System --> Employee : requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml