@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
actor HRM
participant RegisterCollaboratorUI
participant RegisterCollaboratorController
participant Repositories
participant CollaboratorRepository
participant "collaborator:\nCollaborator" as collaborator

activate HRM
HRM -> RegisterCollaboratorUI: Request to register a collaborator
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> HRM: Requests collaborator details
deactivate RegisterCollaboratorUI
HRM -> RegisterCollaboratorUI: Provides collaborator details
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> HRM: Shows details and requests confirmation
deactivate RegisterCollaboratorUI
HRM -> RegisterCollaboratorUI: Confirms details
activate RegisterCollaboratorUI
RegisterCollaboratorUI -> RegisterCollaboratorController: RegisterCollaborator(details)
activate RegisterCollaboratorController
RegisterCollaboratorController -> Repositories: getInstance()
activate Repositories
Repositories -> RegisterCollaboratorController: repositories
deactivate Repositories
RegisterCollaboratorController -> CollaboratorRepository: getCollaboratorRepository()
activate CollaboratorRepository
CollaboratorRepository -> RegisterCollaboratorController: collaboratorRepository
deactivate CollaboratorRepository
RegisterCollaboratorController -> CollaboratorRepository: registerCollaborator(details)
activate CollaboratorRepository
CollaboratorRepository -> collaborator**: create(details)
CollaboratorRepository -> CollaboratorRepository: addCollaborator(collaborator)

activate CollaboratorRepository
CollaboratorRepository -> CollaboratorRepository: validateCollaborator(collaborator)

activate CollaboratorRepository



CollaboratorRepository --> RegisterCollaboratorController: collaborator
deactivate CollaboratorRepository
deactivate CollaboratorRepository
deactivate CollaboratorRepository
RegisterCollaboratorController --> RegisterCollaboratorUI: collaborator
deactivate RegisterCollaboratorController
RegisterCollaboratorUI --> HRM: display operation success
deactivate RegisterCollaboratorUI
deactivate HRM
@enduml
