@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

class HRManager {
    - name: String
    - birthDate: Date
    - admissionDate: Date
    - address: String
    - mobile: String
    - email: String
    - taxpayerNumber: String
    - idDocType: String
    - idNumber: String

    + HRManager(name, birthDate, admissionDate, address, mobile, email, taxpayerNumber, idDocType, idNumber)
    + registerCollaborator()
}

class Job {
    - name: String

    + Job(name)
}

class Collaborator {
    - name: String
    - birthDate: Date
    - admissionDate: Date
    - address: String
    - mobile: String
    - email: String
    - taxpayerNumber: String
    - idDocType: String
    - idNumber: String

    + Collaborator(name, birthDate, admissionDate, address, mobile, email, taxpayerNumber, idDocType, idNumber)
}

HRManager -- Collaborator : registers
HRManager -- Job : creates

@enduml
