@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources\n Manager" as HRM
participant ":RegisterCollaboratorUI" as CollabUI
participant ":RegisterCollaboratorController" as CollabController
participant ":RegisterJobUI" as JobUI
participant ":RegisterJobController" as JobController
participant Repositories
participant "repositories\n:Repositories" as Repos
participant "collaboratorRepository\n:CollaboratorRepository" as CollabRepo
participant "collaborator:Collaborator" as Collaborator
participant "jobRepository\n:JobRepository" as JobRepo
participant "job:Job" as Job

activate HRM

HRM -> CollabUI : asks to register a collaborator
activate CollabUI

CollabUI --> HRM : requests collaborator details (name, birth date, admission date, address, contact info, taxpayer number, ID doc type, ID doc number)
deactivate CollabUI

HRM -> CollabUI: provides collaborator details
activate CollabUI

CollabUI --> HRM : shows details and asks for confirmation
deactivate CollabUI

HRM -> CollabUI : confirms details
activate CollabUI

CollabUI -> CollabController: registerCollaborator(details)
activate CollabController

CollabController -> Repos: getInstance()
activate Repos

Repos --> CollabController: repositories
deactivate Repos

CollabController -> CollabRepo: getCollaboratorRepository()
activate CollabRepo

CollabRepo --> CollabController: collaboratorRepository
deactivate CollabRepo

CollabController -> CollabRepo**: registerCollaborator(details)
activate CollabRepo

CollabRepo -> Collaborator: Collaborator(details)
activate Collaborator

Collaborator -> Collaborator: validateTaxpayerNumber(taxpayer number)
Collaborator -> Collaborator: validateIDDocumentNumber(idDocumentNumber)

Collaborator --> CollabRepo: valid
deactivate Collaborator

CollabRepo -> CollabRepo: addCollaborator(collaborator)
activate CollabRepo

CollabRepo -> CollabRepo: validateCollaborator(collaborator)

CollabRepo --> CollabController: collaborator
deactivate CollabRepo
deactivate CollabRepo

CollabController --> CollabUI: collaborator
deactivate CollabController

CollabUI --> HRM: displays operation success
deactivate CollabUI

HRM -> JobUI : asks to create a new job
activate JobUI

JobUI --> HRM : requests job details
deactivate JobUI

HRM -> JobUI : provides job details
activate JobUI

JobUI --> HRM : shows details and asks for confirmation
deactivate JobUI

HRM -> JobUI : confirms job details
activate JobUI

JobUI -> JobController : registerJob(jobDetails)
activate JobController

JobController -> Repos: getInstance()
activate Repos

Repos --> JobController: repositories
deactivate Repos

JobController -> JobRepo: getJobRepository()
activate JobRepo

JobRepo --> JobController: jobRepository
deactivate JobRepo

JobController -> JobRepo**: registerJob(jobDetails)
activate JobRepo

JobRepo -> Job: Job(jobDetails)
activate Job

Job -> Job: addJob(Job)
activate Job

Job -> Job: validateJob(Job)
activate Job

Job --> JobRepo: job
deactivate Job
deactivate Job

JobRepo -> JobRepo: validateJob(job)
activate JobRepo

JobRepo --> JobController: job
deactivate JobRepo
deactivate JobRepo

JobController --> JobUI : job
deactivate JobController

JobUI --> HRM: displays operation success
deactivate JobUI

deactivate HRM
@enduml
