@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces \nManager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to add a new entry to the agenda
    activate System

        System --> GSM : asks to choose the green space \nfor which want to add the entry
    deactivate System

    GSM -> System : select the desired green space
    activate System

        System --> GSM : shows all the tasks registered in the \nto-do list of the chosen green space \nand asks to select the one want to add
    deactivate System

    GSM -> System : select the desired task and its start and\n end date
    activate System

        System --> GSM : shows all data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

        System --> GSM : displays operation success
    deactivate System

@enduml