@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Collaborator {
   name
   birthdate
   admissionDate
   address
   contactInfo
   idDocumentType
   idDocumentNumber
}

class HRM {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class Skill {
    name
}
class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}



GreenSpace "1" -- "1..*" Collaborator: contains >
Skill "1..*" - "1..*" Collaborator: has <
HRM "1  " -- "1..*" Skill: creates >
Collaborator <|-- HRM
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
@enduml