@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class HRM {
     name
     birthdate
     admission date
     address
     phone number
     email
     identification document
     number
 }

class Team {
    size
    members

}

class Collaborator {
    name
    birthdate
    admission date
    address
    phone number
    email
    identification document
    number
}

class Skills {
    name
}

class Job {
    name
}

class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}


HRM "1" - "1..*" Team : creates >
Collaborator <|-- HRM
Collaborator "1" - "1..*" Skills: has >
Collaborator "1" -- "1" Job: has >
Team "1" -- "1..*" Collaborator: has >
GreenSpace "1" -- "1..*" Collaborator: contains >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark

@enduml