@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class HRM {
     name
     birthdate
     admission date
     address
     phone number
     email
     identification document
     number
 }

class Team {
    size
    members

}

class Collaborator {
    name
    birthdate
    admission date
    address
    phone number
    email
    identification document
    number
}

class Employee {
    name
    email
    position
    phone
}


HRM "1" - "1..*" Team : creates >
Team "1" - "1..*" Collaborator: has >
'Task "*" -- "1" Employee: created by >
Employee "1" -- "*" Task : creates >
'Employee "0..1" -- "1" User: acts as >
Task "*" - "1" Category: cataloged as >
@enduml