@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registerVehicleRepository:\nRegisterVehicleRepository" as RegisterVehicleRepository
participant "vehicle\n:Vehicle" as VEHICLE

activate ADM

        ADM -> UI : asks to register a new vehicle

        activate UI

            UI --> ADM : requests data (plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)

            ADM -> UI : types requested data

            UI --> ADM : shows all data and requests confirmation

            ADM -> UI : confirms data

            UI -> CTRL : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getRegisterVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: registerVehicleRepository
                deactivate PLAT

                CTRL -> RegisterVehicleRepository : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
                activate RegisterVehicleRepository

                RegisterVehicleRepository -> VEHICLE**: registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
                RegisterVehicleRepository -> RegisterVehicleRepository: addVehicle (vehicle)

                 activate RegisterVehicleRepository
                     RegisterVehicleRepository -> RegisterVehicleRepository: validateVehicle(vehicle)
                     activate RegisterVehicleRepository
                         RegisterVehicleRepository --> RegisterVehicleRepository
                     deactivate RegisterVehicleRepository

                     RegisterVehicleRepository --> RegisterVehicleRepository
                 deactivate RegisterVehicleRepository

                                RegisterVehicleRepository --> CTRL : vehicle

                            deactivate RegisterVehicleRepository

            CTRL --> UI: vehicle
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml