@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registerVehicleRepository:\nRegisterVehicleRepository" as RegisterVehicleRepository
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "vehicle\n:Vehicle" as VEHICLE

activate ADM

        ADM -> UI : asks to register a new vehicle

        activate UI

            UI --> ADM : requests data (plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)

            ADM -> UI : types requested data

            UI --> ADM : shows all data and requests confirmation

            ADM -> UI : confirms data
            create CTRL
            UI -> CTRL** : register

            UI -> CTRL : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : registerVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: registerVehicleRepository
                deactivate PLAT

                CTRL -> ORG : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
                activate ORG

                 ORG -> VEHICLE**: registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
                 ORG -> ORG: addVehicle (vehicle)

                 activate ORG
                     ORG -> ORG: validateVehicle(vehicle)
                     activate ORG
                         ORG --> ORG
                     deactivate ORG

                     ORG --> ORG
                 deactivate ORG

                                ORG --> CTRL : vehicle

                            deactivate ORG

            CTRL --> UI: vehicle
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml