@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "registerVehicleRepository:\nRegisterVehicleRepository" as RegisterVehicleRepository
activate ADM

        ADM -> UI : asks to register a new vehicle

        activate UI

            UI --> ADM : requests data (plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)

            ADM -> UI : types requested data

            UI --> ADM : shows all data and requests confirmation

            ADM -> UI : confirms data

            UI -> CTRL : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : registerVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: registerVehicleRepository
                deactivate PLAT

                CTRL -> RegisterVehicleRepository : registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
                activate RegisterVehicleRepository
                ref over RegisterVehicleRepository
                    Register Vehicle

                end ref
                                RegisterVehicleRepository --> CTRL : vehicle

                            deactivate RegisterVehicleRepository

            CTRL --> UI: vehicle
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml