@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "registerVehicleRepository\n:RegisterVehicleRepository" as ORG
participant "vehicle\n:Vehicle" as VEHICLE

autonumber 16
-> ORG: registerVehicle(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)

autonumber 16.1
activate ORG
    group Register Vehicle

        ORG -> VEHICLE**: register(plateNumber, brand,\n model,type, tare, grossWeight,\n currentKms,registrationDate,\nacquisitionDate, serviceFrequency)
        ORG -> ORG: addVehicle (vehicle)

        activate ORG
            ORG -> ORG: validateVehicle(vehicle)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 17
    <-- ORG : task
deactivate ORG


@enduml