@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0
hide circles
hide methods

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class Organization{
    name
    address
}

class VFM{
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}

class GreenSpace {
    name
    address
    dimension
}

class Garden {
}

class MediumSizedPark {
}

class LargeSizedPark {
}

Collaborator <|-- VFM
VFM "1"-"   1..*" Vehicle: registers >
Collaborator "1..*" - "1" GreenSpace: has <
GreenSpace "1" -- "1..*" Vehicle: has >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark
Organization "1" -- "1..*" GreenSpace: owns >
Organization "1   " -- "1..*" Collaborator: works for <


@enduml