@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0
hide circles
hide methods

class Collaborator {
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class VFM{
    name
    birthdate
    admissionDate
    address
    contactInfo
    idDocumentType
    idDocumentNumber
}

class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}

class GreenSpace {
    name
    address
    type
}

class Garden {
    name
    address
    dimension
}

class MediumSizedPark {
    name
    address
    dimension
}

class LargeSizedPark {
    name
    address
    dimension
}

Collaborator <|-- VFM
VFM "1"-"   1..*" Vehicle: registers >
GreenSpace "1" -- "1..*" Collaborator: contains >
GreenSpace "1" -- "1..*" Vehicle: has >
GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark

@enduml