@startuml

hide circles
hide methods

class FleetManager{
    name
    birthdate
    admission date
    address
    phone number
    email
    identification document
    number
}

class Vehicle{
    plate id
    brand
    model
    type
    tare
    gross weight
    current kms
    registration date
    acquisition date
    maintenance/check-up frequency
}


FleetManager "1"-"   1..*" Vehicle: registers >

@enduml