@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":GenerateTeamProposalController" as CTRL
participant Repositories
participant "repositories\n:Repositories" as REP
participant "teamRepository\n:TeamRepository" as TEAMREP
participant "team\n:Team" as TEAM
participant "collaborator\n:Collaborator" as COLLAB

autonumber 13
-> CTRL : generateTeamProposal(minimumSize, maximumSize, skills, collaborators)

autonumber 13.1

activate CTRL
    group Generate Team Proposal

    CTRL -> Repositories: getInstance()
    activate Repositories

        Repositories --> CTRL: repositories
    deactivate Repositories

    CTRL -> REP: getTeamRepository()
    activate REP

        REP --> CTRL: teamRepository
    deactivate REP

    CTRL -> TEAMREP: generateTeamProposal(minimumSize, maximumSize, skills, collaborators)
    activate TEAMREP

        TEAMREP -> TEAM**: Team(minimumSize, maximumSize, collaborators, skills)
        activate TEAM

            loop for each collaborator
            loop for each skill

            TEAM -> COLLAB**: addTeam(skill)
            activate COLLAB

            COLLAB -> COLLAB: analyseCollaborator(skill)
            activate COLLAB

            COLLAB --> TEAM: canJoinTeam
            deactivate COLLAB

            deactivate COLLAB

            end

            end

            TEAM --> TEAMREP: team
            deactivate TEAM

            TEAMREP --> CTRL: team
            deactivate TEAMREP
    end group

    autonumber 14
    <-- CTRL : team

deactivate CTRL


@enduml