@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class ParkUser {
    name
 }

class Survey{

}

class Organization{
    name
    address
}


ParkUser "1..*" -- "1" Survey: fill out >
Survey "1" -- "1" Organization: owns <
@enduml