@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
'José não é como em PPROG ainda
class Collaborator {
     name
     birthdate
     admissionDate
     address
     contactInfo
     idDocumentType
     idDocumentNumber
}

class Organization {
    name
    vatNumber
    website
    phone
    email
    collaborators
}

Organization "1" --> "*" Collaborator : contains

@enduml
